// explain.js — plain-language, non-developer explanations for each scanner rule.
// The scanner's rule labels are technical ("Missing Content-Security-Policy header").
// This turns each finding into: what it means for YOU, and what to do — in en + ko.
// Keyed by rule_id (from scanner.js). Unknown rules fall back to the raw label.

const EXPLAIN = {
  // ---- critical: someone can read your data or use your keys right now ----
  supabase_missing_rls: {
    en: { title: 'A database table is open to the public',
      what: "Anyone on the internet can read this table directly — no login required. If it holds names, emails, or other customer info, that data is exposed right now.",
      fix: "In Supabase, open your table → \"Row Level Security\" and turn RLS ON (there's a one-click button), then add a policy so only the right users can read it." },
    ko: { title: '데이터베이스 테이블이 외부에 열려 있습니다',
      what: '로그인 없이 인터넷의 누구나 이 테이블을 그대로 읽을 수 있습니다. 이름·이메일 등 고객 정보가 들어 있다면 지금 그대로 노출된 상태입니다.',
      fix: 'Supabase에서 해당 테이블 → "Row Level Security(RLS)"를 켜세요(원클릭 버튼이 있습니다). 그다음 올바른 사용자만 읽도록 정책(policy)을 추가하세요.' },
    es: { title: 'Una tabla de tu base de datos está abierta al público',
      what: "Cualquier persona en internet puede leer esta tabla directamente, sin necesidad de iniciar sesión. Si contiene nombres, correos u otra información de clientes, esos datos están expuestos ahora mismo.",
      fix: "En Supabase, abre tu tabla → \"Row Level Security\" y activa RLS (hay un botón de un clic), luego añade una política (policy) para que solo los usuarios correctos puedan leerla." },
    ja: { title: 'データベースのテーブルが誰でも見られる状態です',
      what: 'ログインなしで、インターネット上の誰でもこのテーブルを直接読み取れます。氏名やメールアドレスなど顧客情報が含まれている場合、そのデータは今まさに公開されています。',
      fix: 'Supabaseでテーブルを開き、「Row Level Security」をONにしてください（ワンクリックのボタンがあります）。その後、正しいユーザーだけが読み取れるようにポリシー（policy）を追加してください。' },
    pt: { title: 'Uma tabela do banco de dados está aberta ao público',
      what: "Qualquer pessoa na internet pode ler essa tabela diretamente — sem precisar de login. Se ela contém nomes, e-mails ou outras informações de clientes, esses dados estão expostos agora mesmo.",
      fix: "No Supabase, abra sua tabela → \"Row Level Security\" e ative o RLS (há um botão de um clique). Depois, adicione uma política (policy) para que só os usuários certos possam ler os dados." },
    fr: { title: 'Une table de votre base de données est ouverte au public',
      what: "N'importe qui sur internet peut lire cette table directement — sans avoir besoin de se connecter. Si elle contient des noms, des e-mails ou d'autres infos clients, ces données sont exposées dès maintenant.",
      fix: "Dans Supabase, ouvrez votre table → \"Row Level Security\" et activez le RLS (il y a un bouton en un clic), puis ajoutez une policy (règle d'accès) pour que seuls les bons utilisateurs puissent la lire." },
    de: { title: 'Eine Datenbanktabelle ist öffentlich einsehbar',
      what: 'Jeder im Internet kann diese Tabelle direkt auslesen — ganz ohne Login. Wenn dort Namen, E-Mail-Adressen oder andere Kundendaten liegen, sind diese Daten gerade jetzt offen zugänglich.',
      fix: 'Öffnen Sie in Supabase Ihre Tabelle → "Row Level Security" und schalten Sie RLS ein (dafür gibt es einen Ein-Klick-Button). Fügen Sie danach eine Policy hinzu, damit nur die richtigen Nutzer lesen dürfen.' },
    zh: { title: '数据库表格对外部完全开放',
      what: '互联网上任何人都能直接读取这张表——不需要登录。如果里面存有姓名、邮箱等客户信息,这些数据现在就是暴露状态。',
      fix: '在 Supabase 中打开这张表 → 找到 "Row Level Security",一键开启 RLS,然后添加一条策略(policy),让只有合适的用户才能读取。' },
    snippet: { lang: 'sql', code: `alter table your_table enable row level security;

create policy "Allow read for authenticated users only"
on your_table for select
to authenticated
using ( true );` },
  },
  supabase_service_role_in_client: {
    en: { title: 'A master key to your database is visible in your app',
      what: "Your page contains a Supabase \"service_role\" key. That key bypasses all security — anyone who views your page source gets full read/write access to your entire database.",
      fix: "Remove it from the front-end immediately. In Supabase → Settings → API, regenerate the service_role key, and only ever use the \"anon\" key in the browser." },
    ko: { title: '데이터베이스 마스터 키가 앱에 그대로 보입니다',
      what: '페이지에 Supabase "service_role" 키가 들어 있습니다. 이 키는 모든 보안을 무시하므로, 페이지 소스를 본 사람은 데이터베이스 전체를 읽고 쓸 수 있습니다.',
      fix: '즉시 프런트엔드에서 제거하세요. Supabase → Settings → API에서 service_role 키를 재발급하고, 브라우저에는 반드시 "anon" 키만 쓰세요.' },
    es: { title: 'Una clave maestra de tu base de datos es visible en tu app',
      what: "Tu página contiene una clave \"service_role\" de Supabase. Esa clave evita toda la seguridad — cualquiera que vea el código fuente de tu página obtiene acceso completo de lectura y escritura a toda tu base de datos.",
      fix: "Elimínala del front-end de inmediato. En Supabase → Settings → API, regenera la clave service_role y usa siempre la clave \"anon\" en el navegador." },
    ja: { title: 'データベースのマスターキーがアプリ内に見えています',
      what: 'ページにSupabaseの「service_role」キーが含まれています。このキーはすべてのセキュリティを迂回するため、ページのソースを見た人は誰でもデータベース全体に対する読み書き権限を得てしまいます。',
      fix: '今すぐフロントエンドから削除してください。Supabaseの Settings → API でservice_roleキーを再発行し、ブラウザでは必ず「anon」キーのみを使用してください。' },
    pt: { title: 'Uma chave mestra do seu banco de dados está visível no seu app',
      what: "Sua página contém uma chave \"service_role\" do Supabase. Essa chave ignora toda a segurança — qualquer pessoa que veja o código-fonte da sua página tem acesso total de leitura e escrita a todo o seu banco de dados.",
      fix: "Remova isso do front-end imediatamente. No Supabase → Settings → API, gere uma nova chave service_role e use apenas a chave \"anon\" no navegador." },
    fr: { title: 'Une clé maîtresse de votre base de données est visible dans votre app',
      what: "Votre page contient une clé \"service_role\" de Supabase. Cette clé contourne toute la sécurité — n'importe qui consultant le code source de votre page obtient un accès complet en lecture et écriture à toute votre base de données.",
      fix: "Retirez-la du front-end immédiatement. Dans Supabase → Settings → API, régénérez la clé service_role, et n'utilisez jamais que la clé \"anon\" dans le navigateur." },
    de: { title: 'Ein Master-Schlüssel zu Ihrer Datenbank ist in Ihrer App sichtbar',
      what: 'Ihre Seite enthält einen Supabase-"service_role"-Schlüssel. Dieser Schlüssel umgeht jede Sicherheitsmaßnahme — wer den Seitenquelltext ansieht, bekommt vollen Lese- und Schreibzugriff auf Ihre gesamte Datenbank.',
      fix: 'Entfernen Sie ihn sofort aus dem Frontend. Erzeugen Sie in Supabase → Settings → API einen neuen service_role-Schlüssel und verwenden Sie im Browser ausschließlich den "anon"-Schlüssel.' },
    zh: { title: '应用中暴露了数据库的万能密钥',
      what: '你的页面里包含一个 Supabase "service_role" 密钥。这个密钥能绕过所有安全限制——任何查看页面源代码的人都能对你整个数据库进行读写。',
      fix: '立刻从前端移除它。在 Supabase 里进入 Settings → API,重新生成 service_role 密钥,浏览器端永远只使用 "anon" 密钥。' },
  },
  firebase_rtdb_public: {
    en: { title: 'Your Firebase database is readable by anyone',
      what: "Your Firebase Realtime Database security rules let anyone read the data without logging in.",
      fix: "In Firebase Console → Realtime Database → Rules, require sign-in (e.g. set \".read\" to \"auth != null\") and click Publish." },
    ko: { title: 'Firebase 데이터베이스를 아무나 읽을 수 있습니다',
      what: 'Firebase 실시간 데이터베이스 보안 규칙이 로그인 없이 누구나 데이터를 읽도록 허용하고 있습니다.',
      fix: 'Firebase 콘솔 → Realtime Database → Rules에서 로그인 필요로 바꾸세요(예: ".read"를 "auth != null"로) 후 Publish.' },
    es: { title: 'Tu base de datos de Firebase puede leerla cualquiera',
      what: "Las reglas de seguridad de tu Realtime Database de Firebase permiten que cualquiera lea los datos sin iniciar sesión.",
      fix: "En Firebase Console → Realtime Database → Rules, exige inicio de sesión (por ejemplo, pon \".read\" en \"auth != null\") y haz clic en Publish." },
    ja: { title: 'Firebaseのデータベースが誰でも読み取れる状態です',
      what: 'FirebaseのRealtime Databaseのセキュリティルールが、ログインなしで誰でもデータを読み取れる設定になっています。',
      fix: 'Firebase Console → Realtime Database → Rules で、ログインを必須にしてください（例：".read"を"auth != null"に設定）。その後Publishをクリックしてください。' },
    pt: { title: 'Seu banco de dados do Firebase pode ser lido por qualquer pessoa',
      what: "As regras de segurança do seu Firebase Realtime Database permitem que qualquer pessoa leia os dados sem fazer login.",
      fix: "No Firebase Console → Realtime Database → Rules, exija login (por exemplo, defina \".read\" como \"auth != null\") e clique em Publish." },
    fr: { title: "Votre base de données Firebase peut être lue par n'importe qui",
      what: "Les règles de sécurité de votre Firebase Realtime Database laissent n'importe qui lire les données sans se connecter.",
      fix: "Dans Firebase Console → Realtime Database → Rules, exigez une connexion (par exemple mettez \".read\" à \"auth != null\") puis cliquez sur Publish." },
    de: { title: 'Ihre Firebase-Datenbank kann von jedem gelesen werden',
      what: 'Ihre Sicherheitsregeln für die Firebase Realtime Database erlauben es jedem, die Daten ohne Login zu lesen.',
      fix: 'Verlangen Sie in der Firebase Console → Realtime Database → Rules einen Login (z. B. ".read" auf "auth != null" setzen) und klicken Sie auf Publish.' },
    zh: { title: '你的 Firebase 数据库任何人都能读取',
      what: '你的 Firebase Realtime Database 安全规则允许任何人无需登录就读取数据。',
      fix: '在 Firebase Console → Realtime Database → Rules 中要求登录(比如把 ".read" 设为 "auth != null"),然后点击 Publish。' },
    snippet: { lang: 'json', code: `{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}` },
  },
  firestore_public: {
    en: { title: 'A Firestore collection is readable by anyone',
      what: "Your Firestore security rules let anyone read this collection without logging in.",
      fix: "In Firebase Console → Firestore → Rules, require authentication for reads, then Publish." },
    ko: { title: 'Firestore 컬렉션을 아무나 읽을 수 있습니다',
      what: 'Firestore 보안 규칙이 로그인 없이 누구나 이 컬렉션을 읽도록 허용하고 있습니다.',
      fix: 'Firebase 콘솔 → Firestore → Rules에서 읽기에 인증을 요구하도록 바꾸고 Publish.' },
    es: { title: 'Una colección de Firestore puede leerla cualquiera',
      what: "Tus reglas de seguridad de Firestore permiten que cualquiera lea esta colección sin iniciar sesión.",
      fix: "En Firebase Console → Firestore → Rules, exige autenticación para las lecturas y luego haz clic en Publish." },
    ja: { title: 'Firestoreのコレクションが誰でも読み取れる状態です',
      what: 'Firestoreのセキュリティルールが、ログインなしで誰でもこのコレクションを読み取れる設定になっています。',
      fix: 'Firebase Console → Firestore → Rules で読み取りに認証を必須にし、Publishしてください。' },
    pt: { title: 'Uma coleção do Firestore pode ser lida por qualquer pessoa',
      what: "As regras de segurança do seu Firestore permitem que qualquer pessoa leia essa coleção sem fazer login.",
      fix: "No Firebase Console → Firestore → Rules, exija autenticação para leitura e depois clique em Publish." },
    fr: { title: "Une collection Firestore peut être lue par n'importe qui",
      what: "Les règles de sécurité de votre Firestore laissent n'importe qui lire cette collection sans se connecter.",
      fix: "Dans Firebase Console → Firestore → Rules, exigez une authentification pour la lecture, puis cliquez sur Publish." },
    de: { title: 'Eine Firestore-Sammlung kann von jedem gelesen werden',
      what: 'Ihre Firestore-Sicherheitsregeln erlauben es jedem, diese Sammlung ohne Login zu lesen.',
      fix: 'Verlangen Sie in der Firebase Console → Firestore → Rules eine Authentifizierung für Lesezugriffe und klicken Sie dann auf Publish.' },
    zh: { title: 'Firestore 集合任何人都能读取',
      what: '你的 Firestore 安全规则允许任何人无需登录就读取这个集合。',
      fix: '在 Firebase Console → Firestore → Rules 中要求读取时进行身份验证,然后点击 Publish。' },
    snippet: { lang: 'rules', code: `rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}` },
  },
  exposed_env: {
    en: { title: 'Your secret settings file (.env) can be downloaded',
      what: "Your .env file — which usually holds passwords and API keys — is downloadable by anyone at yoursite/.env.",
      fix: "It should never be deployed publicly. Remove it from your public/deploy folder, and rotate any keys or passwords that were inside it." },
    ko: { title: '비밀 설정 파일(.env)을 다운로드할 수 있습니다',
      what: '보통 비밀번호·API 키가 담긴 .env 파일을 누구나 yoursite/.env 로 내려받을 수 있습니다.',
      fix: '.env는 공개 배포되면 안 됩니다. 공개/배포 폴더에서 제거하고, 그 안에 있던 키·비밀번호는 전부 새로 발급하세요.' },
    es: { title: 'Tu archivo de configuración secreto (.env) se puede descargar',
      what: "Tu archivo .env — que normalmente contiene contraseñas y claves de API — se puede descargar en tusitio/.env.",
      fix: "Nunca debería estar publicado. Elimínalo de tu carpeta pública/de despliegue y renueva todas las claves o contraseñas que contenía." },
    ja: { title: '秘密の設定ファイル（.env）がダウンロードできる状態です',
      what: '通常パスワードやAPIキーが入っている.envファイルが、yoursite/.env として誰でもダウンロードできる状態です。',
      fix: '.envは絶対に公開デプロイしてはいけません。公開/デプロイ用フォルダから削除し、中に含まれていたキーやパスワードはすべて再発行してください。' },
    pt: { title: 'Seu arquivo de configurações secretas (.env) pode ser baixado',
      what: "Seu arquivo .env — que geralmente guarda senhas e chaves de API — pode ser baixado por qualquer pessoa em seusite/.env.",
      fix: "Ele nunca deveria ser publicado. Remova-o da sua pasta pública/de deploy e gere novas chaves e senhas para tudo o que estava nele." },
    fr: { title: 'Votre fichier de configuration secret (.env) peut être téléchargé',
      what: "Votre fichier .env — qui contient généralement des mots de passe et des clés API — peut être téléchargé par n'importe qui à l'adresse votresite/.env.",
      fix: "Il ne devrait jamais être publié en ligne. Retirez-le de votre dossier public/de déploiement, et changez toutes les clés ou mots de passe qui s'y trouvaient." },
    de: { title: 'Ihre geheime Konfigurationsdatei (.env) kann heruntergeladen werden',
      what: 'Ihre .env-Datei — die meist Passwörter und API-Schlüssel enthält — kann jeder unter ihreseite/.env herunterladen.',
      fix: 'Sie darf niemals öffentlich bereitgestellt werden. Entfernen Sie sie aus Ihrem öffentlichen/Deploy-Ordner und tauschen Sie alle darin enthaltenen Schlüssel und Passwörter aus.' },
    zh: { title: '你的密钥配置文件(.env)可以被下载',
      what: '你的 .env 文件通常存有密码和 API 密钥,现在任何人都能通过 yoursite/.env 下载它。',
      fix: '这个文件绝不应该被公开部署。把它从公开/部署目录中删除,并把里面的所有密钥和密码全部更换。' },
  },
  stripe_secret: {
    en: { title: 'Your Stripe secret key is exposed',
      what: "A Stripe secret key is visible in your app. Anyone who finds it can create charges and refunds on your account.",
      fix: "Roll (regenerate) the key in your Stripe dashboard now, and keep secret keys on the server only — never in front-end code." },
    ko: { title: 'Stripe 비밀 키가 노출됐습니다',
      what: '앱에 Stripe 비밀 키가 보입니다. 발견한 사람은 당신 계정으로 결제·환불을 만들 수 있습니다.',
      fix: 'Stripe 대시보드에서 키를 지금 재발급하고, 비밀 키는 서버에만 두세요 — 프런트엔드 코드에 절대 넣지 마세요.' },
    es: { title: 'Tu clave secreta de Stripe está expuesta',
      what: "Una clave secreta de Stripe es visible en tu app. Cualquiera que la encuentre puede generar cobros y reembolsos en tu cuenta.",
      fix: "Renueva (regenera) la clave ahora en tu panel de Stripe, y mantén las claves secretas solo en el servidor — nunca en el código del front-end." },
    ja: { title: 'Stripeのシークレットキーが漏えいしています',
      what: 'アプリ内にStripeのシークレットキーが見えています。見つけた人は誰でもあなたのアカウントで請求や返金を作成できます。',
      fix: '今すぐStripeダッシュボードでキーを再発行し、シークレットキーはサーバー側だけに保管してください — フロントエンドのコードには絶対に入れないでください。' },
    pt: { title: 'Sua chave secreta do Stripe está exposta',
      what: "Uma chave secreta do Stripe está visível no seu app. Quem encontrar essa chave pode gerar cobranças e reembolsos na sua conta.",
      fix: "Gere uma nova chave agora mesmo no painel do Stripe, e mantenha chaves secretas apenas no servidor — nunca no código do front-end." },
    fr: { title: 'Votre clé secrète Stripe est exposée',
      what: "Une clé secrète Stripe est visible dans votre app. Toute personne qui la trouve peut créer des paiements et des remboursements sur votre compte.",
      fix: "Régénérez la clé maintenant dans votre tableau de bord Stripe, et gardez les clés secrètes uniquement sur le serveur — jamais dans le code front-end." },
    de: { title: 'Ihr geheimer Stripe-Schlüssel ist offengelegt',
      what: 'Ein geheimer Stripe-Schlüssel ist in Ihrer App sichtbar. Wer ihn findet, kann über Ihr Konto Zahlungen und Rückerstattungen auslösen.',
      fix: 'Erzeugen Sie den Schlüssel jetzt in Ihrem Stripe-Dashboard neu, und bewahren Sie geheime Schlüssel nur auf dem Server auf — niemals im Frontend-Code.' },
    zh: { title: '你的 Stripe 密钥泄露了',
      what: '应用中暴露了一个 Stripe 密钥。任何找到它的人都能用你的账户发起收款和退款。',
      fix: '现在就去 Stripe 后台重新生成密钥,密钥只能保存在服务器端——绝不能出现在前端代码里。' },
  },
  openai_key: {
    en: { title: 'Your OpenAI API key is exposed',
      what: "An OpenAI key is visible in your app. Anyone can copy it and run up usage charges on your bill.",
      fix: "Revoke the key in your OpenAI dashboard and create a new one, kept on the server only." },
    ko: { title: 'OpenAI API 키가 노출됐습니다',
      what: '앱에 OpenAI 키가 보입니다. 누구나 복사해 당신 앞으로 사용 요금을 발생시킬 수 있습니다.',
      fix: 'OpenAI 대시보드에서 키를 폐기하고 새 키를 발급해 서버에만 두세요.' },
    es: { title: 'Tu clave de API de OpenAI está expuesta',
      what: "Una clave de OpenAI es visible en tu app. Cualquiera puede copiarla y generar cargos de uso en tu factura.",
      fix: "Revoca la clave en tu panel de OpenAI y crea una nueva, manteniéndola solo en el servidor." },
    ja: { title: 'OpenAIのAPIキーが漏えいしています',
      what: 'アプリ内にOpenAIのキーが見えています。誰でもコピーして、あなたの請求に利用料金を発生させることができます。',
      fix: 'OpenAIダッシュボードでキーを無効化し、新しいキーを作成してサーバー側だけに保管してください。' },
    pt: { title: 'Sua chave de API da OpenAI está exposta',
      what: "Uma chave da OpenAI está visível no seu app. Qualquer pessoa pode copiá-la e gerar cobranças de uso na sua fatura.",
      fix: "Revogue a chave no painel da OpenAI e crie uma nova, mantendo-a apenas no servidor." },
    fr: { title: 'Votre clé API OpenAI est exposée',
      what: "Une clé OpenAI est visible dans votre app. N'importe qui peut la copier et générer des frais d'utilisation sur votre facture.",
      fix: "Révoquez la clé dans votre tableau de bord OpenAI et créez-en une nouvelle, à garder uniquement sur le serveur." },
    de: { title: 'Ihr OpenAI-API-Schlüssel ist offengelegt',
      what: 'Ein OpenAI-Schlüssel ist in Ihrer App sichtbar. Jeder kann ihn kopieren und auf Ihre Rechnung Nutzungskosten verursachen.',
      fix: 'Widerrufen Sie den Schlüssel in Ihrem OpenAI-Dashboard und erstellen Sie einen neuen, der nur auf dem Server gespeichert wird.' },
    zh: { title: '你的 OpenAI API 密钥泄露了',
      what: '应用中暴露了一个 OpenAI 密钥。任何人都能复制它,把使用费用记到你的账单上。',
      fix: '在 OpenAI 后台吊销这个密钥,创建一个新密钥,只保存在服务器端。' },
  },
  anthropic_key: {
    en: { title: 'Your Anthropic API key is exposed',
      what: "An Anthropic (Claude) key is visible in your app. Anyone can copy it and spend on your account.",
      fix: "Revoke the key in your Anthropic Console and create a new one, kept on the server only." },
    ko: { title: 'Anthropic API 키가 노출됐습니다',
      what: '앱에 Anthropic(Claude) 키가 보입니다. 누구나 복사해 당신 계정으로 비용을 쓸 수 있습니다.',
      fix: 'Anthropic 콘솔에서 키를 폐기하고 새 키를 발급해 서버에만 두세요.' },
    es: { title: 'Tu clave de API de Anthropic está expuesta',
      what: "Una clave de Anthropic (Claude) es visible en tu app. Cualquiera puede copiarla y generar gastos en tu cuenta.",
      fix: "Revoca la clave en Anthropic Console y crea una nueva, manteniéndola solo en el servidor." },
    ja: { title: 'AnthropicのAPIキーが漏えいしています',
      what: 'アプリ内にAnthropic（Claude）のキーが見えています。誰でもコピーして、あなたのアカウントで費用を発生させることができます。',
      fix: 'Anthropic Consoleでキーを無効化し、新しいキーを作成してサーバー側だけに保管してください。' },
    pt: { title: 'Sua chave de API da Anthropic está exposta',
      what: "Uma chave da Anthropic (Claude) está visível no seu app. Qualquer pessoa pode copiá-la e gastar usando sua conta.",
      fix: "Revogue a chave no Anthropic Console e crie uma nova, mantendo-a apenas no servidor." },
    fr: { title: 'Votre clé API Anthropic est exposée',
      what: "Une clé Anthropic (Claude) est visible dans votre app. N'importe qui peut la copier et dépenser sur votre compte.",
      fix: "Révoquez la clé dans votre Anthropic Console et créez-en une nouvelle, à garder uniquement sur le serveur." },
    de: { title: 'Ihr Anthropic-API-Schlüssel ist offengelegt',
      what: 'Ein Anthropic-Schlüssel (Claude) ist in Ihrer App sichtbar. Jeder kann ihn kopieren und auf Ihre Kosten nutzen.',
      fix: 'Widerrufen Sie den Schlüssel in der Anthropic Console und erstellen Sie einen neuen, der nur auf dem Server gespeichert wird.' },
    zh: { title: '你的 Anthropic API 密钥泄露了',
      what: '应用中暴露了一个 Anthropic(Claude)密钥。任何人都能复制它,花费记在你的账户上。',
      fix: '在 Anthropic Console 吊销这个密钥,创建一个新密钥,只保存在服务器端。' },
  },
  aws_key: {
    en: { title: 'An AWS access key is exposed',
      what: "An AWS key is visible in your app. AWS keys can unlock storage, servers, and databases — this is high-risk.",
      fix: "Deactivate the key in the AWS IAM console immediately and create a new one with least-privilege access, kept on the server only." },
    ko: { title: 'AWS 액세스 키가 노출됐습니다',
      what: '앱에 AWS 키가 보입니다. AWS 키는 스토리지·서버·DB를 열 수 있어 위험이 큽니다.',
      fix: 'AWS IAM 콘솔에서 즉시 비활성화하고, 최소 권한의 새 키를 발급해 서버에만 두세요.' },
    es: { title: 'Una clave de acceso de AWS está expuesta',
      what: "Una clave de AWS es visible en tu app. Las claves de AWS pueden dar acceso a almacenamiento, servidores y bases de datos — esto es de alto riesgo.",
      fix: "Desactiva la clave en la consola de AWS IAM de inmediato y crea una nueva con permisos mínimos, manteniéndola solo en el servidor." },
    ja: { title: 'AWSのアクセスキーが漏えいしています',
      what: 'アプリ内にAWSのキーが見えています。AWSのキーはストレージ・サーバー・データベースを開けてしまうため、リスクが非常に高いです。',
      fix: 'AWS IAM コンソールで直ちにキーを無効化し、必要最小限の権限を持つ新しいキーを作成してサーバー側だけに保管してください。' },
    pt: { title: 'Uma chave de acesso da AWS está exposta',
      what: "Uma chave da AWS está visível no seu app. Chaves da AWS podem abrir armazenamento, servidores e bancos de dados — o risco é alto.",
      fix: "Desative a chave imediatamente no console AWS IAM e crie uma nova com o mínimo de permissões necessárias, mantendo-a apenas no servidor." },
    fr: { title: "Une clé d'accès AWS est exposée",
      what: "Une clé AWS est visible dans votre app. Les clés AWS peuvent débloquer du stockage, des serveurs et des bases de données — le risque est élevé.",
      fix: "Désactivez la clé immédiatement dans la console AWS IAM et créez-en une nouvelle avec le minimum de droits nécessaires, à garder uniquement sur le serveur." },
    de: { title: 'Ein AWS-Zugriffsschlüssel ist offengelegt',
      what: 'Ein AWS-Schlüssel ist in Ihrer App sichtbar. AWS-Schlüssel können Speicher, Server und Datenbanken freischalten — das ist ein hohes Risiko.',
      fix: 'Deaktivieren Sie den Schlüssel sofort in der AWS IAM-Konsole und erstellen Sie einen neuen mit minimalen Rechten, der nur auf dem Server gespeichert wird.' },
    zh: { title: 'AWS 访问密钥泄露了',
      what: '应用中暴露了一个 AWS 密钥。AWS 密钥能打开存储、服务器和数据库的大门——风险非常高。',
      fix: '立刻在 AWS IAM 控制台停用这个密钥,创建一个权限最小化的新密钥,只保存在服务器端。' },
  },
  private_key: {
    en: { title: 'A private key is exposed',
      what: "A cryptographic private key is visible in your app. These are meant to be secret and can be used to impersonate your service.",
      fix: "Remove it from anything public, and generate a fresh key pair. Treat the exposed one as compromised." },
    ko: { title: '개인 키(private key)가 노출됐습니다',
      what: '앱에 암호용 개인 키가 보입니다. 이 키는 비밀이어야 하며, 서비스를 사칭하는 데 쓰일 수 있습니다.',
      fix: '공개된 곳에서 제거하고 키 쌍을 새로 생성하세요. 노출된 키는 이미 유출된 것으로 간주하세요.' },
    es: { title: 'Una clave privada está expuesta',
      what: "Una clave privada criptográfica es visible en tu app. Estas claves deben mantenerse en secreto y pueden usarse para suplantar tu servicio.",
      fix: "Elimínala de cualquier lugar público y genera un par de claves nuevo. Trata la clave expuesta como comprometida." },
    ja: { title: '秘密鍵（private key）が漏えいしています',
      what: 'アプリ内に暗号用の秘密鍵が見えています。これは本来秘密にすべきもので、あなたのサービスになりすますために悪用される可能性があります。',
      fix: '公開されている場所からすべて削除し、新しい鍵ペアを生成してください。漏えいした鍵はすでに悪用された可能性があるものとして扱ってください。' },
    pt: { title: 'Uma chave privada está exposta',
      what: "Uma chave criptográfica privada está visível no seu app. Ela deveria ser secreta e pode ser usada para se passar pelo seu serviço.",
      fix: "Remova-a de qualquer lugar público e gere um novo par de chaves. Trate a chave exposta como comprometida." },
    fr: { title: 'Une clé privée est exposée',
      what: "Une clé privée cryptographique est visible dans votre app. Elle est censée rester secrète et peut être utilisée pour usurper votre service.",
      fix: "Retirez-la de tout endroit public et générez une nouvelle paire de clés. Considérez la clé exposée comme compromise." },
    de: { title: 'Ein privater Schlüssel ist offengelegt',
      what: 'Ein kryptografischer privater Schlüssel ist in Ihrer App sichtbar. Solche Schlüssel sollen geheim bleiben und können genutzt werden, um sich als Ihr Dienst auszugeben.',
      fix: 'Entfernen Sie ihn aus allem Öffentlichen und erzeugen Sie ein neues Schlüsselpaar. Behandeln Sie den offengelegten Schlüssel als kompromittiert.' },
    zh: { title: '私钥泄露了',
      what: '应用中暴露了一个加密私钥。这类密钥本应保密,一旦泄露可能被用来冒充你的服务。',
      fix: '把它从任何公开位置移除,重新生成一对新密钥。已泄露的这个应视为已经被攻破。' },
  },
  // ---- high ----
  exposed_git: {
    en: { title: 'Your source code history (.git) is exposed',
      what: "Your /.git folder can be downloaded, which can leak your full source code and any secrets in its history.",
      fix: "Remove the .git folder from your deployed/public files so it isn't served to visitors." },
    ko: { title: '소스코드 이력(.git)이 노출됐습니다',
      what: '/.git 폴더를 내려받을 수 있어, 전체 소스코드와 이력 속 비밀이 새어나갈 수 있습니다.',
      fix: '배포/공개 파일에서 .git 폴더를 제거해 방문자에게 제공되지 않게 하세요.' },
    es: { title: 'El historial de tu código fuente (.git) está expuesto',
      what: "Tu carpeta /.git se puede descargar, lo que puede filtrar todo tu código fuente y cualquier secreto guardado en su historial.",
      fix: "Elimina la carpeta .git de tus archivos publicados/desplegados para que no se sirva a los visitantes." },
    ja: { title: 'ソースコードの履歴（.git）が漏えいしています',
      what: '/.gitフォルダがダウンロード可能な状態になっており、ソースコード全体や履歴内の秘密情報が漏えいする可能性があります。',
      fix: '公開/デプロイ用ファイルから.gitフォルダを削除し、訪問者に配信されないようにしてください。' },
    pt: { title: 'O histórico do seu código-fonte (.git) está exposto',
      what: "Sua pasta /.git pode ser baixada, o que pode vazar todo o seu código-fonte e qualquer segredo guardado no histórico.",
      fix: "Remova a pasta .git dos seus arquivos públicos/de deploy para que ela não seja servida aos visitantes." },
    fr: { title: "L'historique de votre code source (.git) est exposé",
      what: "Votre dossier /.git peut être téléchargé, ce qui peut révéler tout votre code source et les secrets présents dans son historique.",
      fix: "Retirez le dossier .git de vos fichiers publics/déployés pour qu'il ne soit plus accessible aux visiteurs." },
    de: { title: 'Ihre Quellcode-Historie (.git) ist offengelegt',
      what: 'Ihr /.git-Ordner kann heruntergeladen werden, wodurch Ihr gesamter Quellcode und alle Geheimnisse aus der Historie durchsickern können.',
      fix: 'Entfernen Sie den .git-Ordner aus Ihren veröffentlichten/bereitgestellten Dateien, damit er nicht an Besucher ausgeliefert wird.' },
    zh: { title: '你的源代码历史记录(.git)泄露了',
      what: '你的 /.git 文件夹可以被下载,这会泄露你的全部源代码以及历史记录中的所有敏感信息。',
      fix: '把 .git 文件夹从已部署/公开的文件中删除,不要让访客能访问到它。' },
  },
  // ---- medium ----
  cors_wildcard: {
    en: { title: 'Your API accepts requests from any website',
      what: "Your server sends \"Access-Control-Allow-Origin: *\", so any other website can call your API from a visitor's browser.",
      fix: "Restrict this to only your own domain(s) instead of \"*\" in your server/API settings." },
    ko: { title: 'API가 아무 웹사이트의 요청이나 받습니다',
      what: '서버가 "Access-Control-Allow-Origin: *"를 보내고 있어, 다른 어떤 웹사이트든 방문자 브라우저에서 당신 API를 호출할 수 있습니다.',
      fix: '서버/API 설정에서 "*" 대신 당신 도메인만 허용하도록 제한하세요.' },
    es: { title: 'Tu API acepta solicitudes de cualquier sitio web',
      what: "Tu servidor envía \"Access-Control-Allow-Origin: *\", así que cualquier otro sitio web puede llamar a tu API desde el navegador de un visitante.",
      fix: "En la configuración de tu servidor/API, restringe esto solo a tu(s) propio(s) dominio(s) en lugar de \"*\"." },
    ja: { title: 'あなたのAPIがどのウェブサイトからのリクエストも受け付けています',
      what: 'サーバーが「Access-Control-Allow-Origin: *」を送信しているため、他のどのウェブサイトからでも訪問者のブラウザ経由であなたのAPIを呼び出せてしまいます。',
      fix: 'サーバー/APIの設定で、「*」の代わりに自分のドメインのみを許可するように制限してください。' },
    pt: { title: 'Sua API aceita solicitações de qualquer site',
      what: "Seu servidor envia \"Access-Control-Allow-Origin: *\", então qualquer outro site pode chamar sua API a partir do navegador de um visitante.",
      fix: "Restrinja isso para apenas o(s) seu(s) próprio(s) domínio(s) em vez de \"*\" nas configurações do servidor/API." },
    fr: { title: "Votre API accepte les requêtes de n'importe quel site",
      what: "Votre serveur envoie \"Access-Control-Allow-Origin: *\", donc n'importe quel autre site peut appeler votre API depuis le navigateur d'un visiteur.",
      fix: "Limitez cela à votre (ou vos) propre(s) domaine(s) au lieu de \"*\" dans les paramètres de votre serveur/API." },
    de: { title: 'Ihre API akzeptiert Anfragen von jeder Website',
      what: 'Ihr Server sendet "Access-Control-Allow-Origin: *", sodass jede beliebige Website Ihre API über den Browser eines Besuchers aufrufen kann.',
      fix: 'Beschränken Sie das in Ihren Server-/API-Einstellungen auf Ihre eigene(n) Domain(s) statt "*".' },
    zh: { title: '你的 API 接受任何网站发来的请求',
      what: '你的服务器发送了 "Access-Control-Allow-Origin: *",这意味着任何其他网站都能借用访客浏览器调用你的 API。',
      fix: '在服务器/API 设置中把 "*" 改成只允许你自己的域名。' },
  },
  // ---- low ----
  mixed_content: {
    en: { title: 'Your secure page loads some insecure content',
      what: "Your HTTPS page pulls in some http:// resources. Browsers may block them, and it slightly weakens security.",
      fix: "Change those http:// links to https://." },
    ko: { title: '보안 페이지가 일부 비보안 콘텐츠를 불러옵니다',
      what: 'HTTPS 페이지가 일부 http:// 리소스를 불러옵니다. 브라우저가 차단할 수 있고 보안이 약해집니다.',
      fix: '해당 http:// 링크를 https:// 로 바꾸세요.' },
    es: { title: 'Tu página segura carga contenido no seguro',
      what: "Tu página HTTPS carga algunos recursos http://. Los navegadores pueden bloquearlos, y esto debilita ligeramente la seguridad.",
      fix: "Cambia esos enlaces http:// a https://." },
    ja: { title: '安全なページが一部安全でないコンテンツを読み込んでいます',
      what: 'HTTPSのページが一部http://のリソースを読み込んでいます。ブラウザによってブロックされる場合があり、セキュリティもわずかに弱まります。',
      fix: 'それらのhttp://のリンクをhttps://に変更してください。' },
    pt: { title: 'Sua página segura carrega algum conteúdo inseguro',
      what: "Sua página HTTPS carrega alguns recursos http://. Os navegadores podem bloqueá-los, e isso enfraquece um pouco a segurança.",
      fix: "Troque esses links http:// para https://." },
    fr: { title: 'Votre page sécurisée charge du contenu non sécurisé',
      what: "Votre page HTTPS charge des ressources en http://. Les navigateurs peuvent les bloquer, et cela affaiblit légèrement la sécurité.",
      fix: "Changez ces liens http:// en https://." },
    de: { title: 'Ihre sichere Seite lädt teilweise unsichere Inhalte',
      what: 'Ihre HTTPS-Seite lädt einige http://-Ressourcen. Browser können diese blockieren, und es schwächt die Sicherheit leicht.',
      fix: 'Ändern Sie diese http://-Links zu https://.' },
    zh: { title: '你的安全页面加载了部分不安全内容',
      what: '你的 HTTPS 页面引用了一些 http:// 资源。浏览器可能会拦截它们,也会稍微削弱安全性。',
      fix: '把这些 http:// 链接改成 https://。' },
  },
  hdr_csp: {
    en: { title: 'Missing a browser safety header (CSP)',
      what: "A Content-Security-Policy helps block malicious scripts. It's missing — not urgent, but worth adding.",
      fix: "Add a Content-Security-Policy header (via your host's settings) once the bigger items are handled." },
    ko: { title: '브라우저 안전 헤더(CSP)가 없습니다',
      what: 'Content-Security-Policy는 악성 스크립트를 막아줍니다. 지금은 없습니다 — 급하진 않지만 추가하면 좋습니다.',
      fix: '더 중요한 항목부터 해결한 뒤, 호스팅 설정에서 Content-Security-Policy 헤더를 추가하세요.' },
    es: { title: 'Falta un encabezado de seguridad del navegador (CSP)',
      what: "Un Content-Security-Policy ayuda a bloquear scripts maliciosos. No lo tienes — no es urgente, pero conviene añadirlo.",
      fix: "Añade un encabezado Content-Security-Policy (desde la configuración de tu hosting) una vez resueltos los puntos más importantes." },
    ja: { title: 'ブラウザの安全ヘッダー（CSP）が設定されていません',
      what: 'Content-Security-Policyは悪意のあるスクリプトをブロックするのに役立ちます。現在設定されていません — 緊急ではありませんが、追加する価値はあります。',
      fix: 'より重要な項目に対応した後、ホスティングの設定でContent-Security-Policyヘッダーを追加してください。' },
    pt: { title: 'Falta um cabeçalho de segurança do navegador (CSP)',
      what: "Um Content-Security-Policy ajuda a bloquear scripts maliciosos. Ele está faltando — não é urgente, mas vale a pena adicionar.",
      fix: "Adicione um cabeçalho Content-Security-Policy (nas configurações da sua hospedagem) depois de resolver os itens mais importantes." },
    fr: { title: 'Il manque un en-tête de sécurité du navigateur (CSP)',
      what: "Un Content-Security-Policy aide à bloquer les scripts malveillants. Il est absent — pas urgent, mais utile à ajouter.",
      fix: "Ajoutez un en-tête Content-Security-Policy (dans les paramètres de votre hébergeur) une fois les points plus importants réglés." },
    de: { title: 'Ein Browser-Sicherheitsheader (CSP) fehlt',
      what: 'Eine Content-Security-Policy hilft, bösartige Skripte zu blockieren. Sie fehlt bei Ihnen — nicht dringend, aber sinnvoll nachzurüsten.',
      fix: 'Fügen Sie, sobald die größeren Punkte erledigt sind, über die Einstellungen Ihres Hosters einen Content-Security-Policy-Header hinzu.' },
    zh: { title: '缺少浏览器安全头(CSP)',
      what: 'Content-Security-Policy 能帮助拦截恶意脚本。你现在没有设置——不紧急,但值得加上。',
      fix: '等更重要的问题处理完后,在你的托管平台设置里添加 Content-Security-Policy 头。' },
  },
  hdr_hsts: {
    en: { title: 'Missing an HTTPS-enforcement header (HSTS)',
      what: "HSTS tells browsers to always use the secure HTTPS version of your site. Missing it is a minor risk.",
      fix: "Add a Strict-Transport-Security header in your host's settings." },
    ko: { title: 'HTTPS 강제 헤더(HSTS)가 없습니다',
      what: 'HSTS는 브라우저가 항상 보안 HTTPS로 접속하게 합니다. 없어도 위험은 작습니다.',
      fix: '호스팅 설정에서 Strict-Transport-Security 헤더를 추가하세요.' },
    es: { title: 'Falta un encabezado que exige HTTPS (HSTS)',
      what: "HSTS indica a los navegadores que usen siempre la versión segura HTTPS de tu sitio. Si falta, el riesgo es menor.",
      fix: "Añade un encabezado Strict-Transport-Security en la configuración de tu hosting." },
    ja: { title: 'HTTPSを強制するヘッダー（HSTS）が設定されていません',
      what: 'HSTSはブラウザに対して常に安全なHTTPS版のサイトを使うよう指示するものです。設定されていなくてもリスクは小さいです。',
      fix: 'ホスティングの設定でStrict-Transport-Securityヘッダーを追加してください。' },
    pt: { title: 'Falta um cabeçalho que força o uso de HTTPS (HSTS)',
      what: "O HSTS diz aos navegadores para sempre usar a versão segura (HTTPS) do seu site. A falta dele é um risco pequeno.",
      fix: "Adicione um cabeçalho Strict-Transport-Security nas configurações da sua hospedagem." },
    fr: { title: "Il manque un en-tête forçant l'HTTPS (HSTS)",
      what: "Le HSTS indique aux navigateurs de toujours utiliser la version sécurisée (HTTPS) de votre site. Son absence représente un risque mineur.",
      fix: "Ajoutez un en-tête Strict-Transport-Security dans les paramètres de votre hébergeur." },
    de: { title: 'Ein HTTPS-Erzwingungsheader (HSTS) fehlt',
      what: 'HSTS sagt Browsern, immer die sichere HTTPS-Version Ihrer Website zu verwenden. Ohne ihn besteht ein kleines Risiko.',
      fix: 'Fügen Sie in den Einstellungen Ihres Hosters einen Strict-Transport-Security-Header hinzu.' },
    zh: { title: '缺少强制 HTTPS 的安全头(HSTS)',
      what: 'HSTS 告诉浏览器始终使用你网站的安全 HTTPS 版本。缺少它风险较小。',
      fix: '在你的托管平台设置里添加 Strict-Transport-Security 头。' },
  },
  hdr_xfo: {
    en: { title: 'Missing clickjacking protection',
      what: "Without a frame-protection header, your site could be embedded inside a malicious page to trick your users.",
      fix: "Add \"X-Frame-Options: DENY\" (or a CSP frame-ancestors rule) in your host's settings." },
    ko: { title: '클릭재킹 보호가 없습니다',
      what: '프레임 보호 헤더가 없으면, 당신 사이트가 악성 페이지 안에 삽입돼 사용자를 속이는 데 쓰일 수 있습니다.',
      fix: '호스팅 설정에서 "X-Frame-Options: DENY"(또는 CSP frame-ancestors 규칙)를 추가하세요.' },
    es: { title: 'Falta protección contra clickjacking',
      what: "Sin un encabezado de protección de frames, tu sitio podría incrustarse dentro de una página maliciosa para engañar a tus usuarios.",
      fix: "Añade \"X-Frame-Options: DENY\" (o una regla frame-ancestors de CSP) en la configuración de tu hosting." },
    ja: { title: 'クリックジャッキング対策が設定されていません',
      what: 'フレーム保護ヘッダーがないと、悪意のあるページの中にあなたのサイトが埋め込まれ、ユーザーをだますために悪用される可能性があります。',
      fix: 'ホスティングの設定で「X-Frame-Options: DENY」（またはCSPのframe-ancestorsルール）を追加してください。' },
    pt: { title: 'Falta proteção contra clickjacking',
      what: "Sem um cabeçalho de proteção contra frames, seu site pode ser incorporado dentro de uma página maliciosa para enganar seus usuários.",
      fix: "Adicione \"X-Frame-Options: DENY\" (ou uma regra frame-ancestors no CSP) nas configurações da sua hospedagem." },
    fr: { title: 'Il manque une protection contre le clickjacking',
      what: "Sans en-tête de protection contre les frames, votre site pourrait être intégré dans une page malveillante pour piéger vos utilisateurs.",
      fix: "Ajoutez \"X-Frame-Options: DENY\" (ou une règle frame-ancestors dans le CSP) dans les paramètres de votre hébergeur." },
    de: { title: 'Schutz vor Clickjacking fehlt',
      what: 'Ohne einen Frame-Schutz-Header könnte Ihre Website in eine bösartige Seite eingebettet werden, um Ihre Nutzer zu täuschen.',
      fix: 'Fügen Sie in den Einstellungen Ihres Hosters "X-Frame-Options: DENY" hinzu (oder eine CSP-frame-ancestors-Regel).' },
    zh: { title: '缺少点击劫持防护',
      what: '没有帧保护头,你的网站可能被嵌入到恶意页面中,用来欺骗你的用户。',
      fix: '在你的托管平台设置里添加 "X-Frame-Options: DENY"(或者一条 CSP frame-ancestors 规则)。' },
  },
  hdr_xcto: {
    en: { title: 'Missing a minor content-type header',
      what: "A small hardening header (X-Content-Type-Options) is missing. Very low priority.",
      fix: "Add \"X-Content-Type-Options: nosniff\" when convenient." },
    ko: { title: '사소한 콘텐츠 타입 헤더가 없습니다',
      what: '작은 보강 헤더(X-Content-Type-Options)가 없습니다. 우선순위 매우 낮음.',
      fix: '여유 될 때 "X-Content-Type-Options: nosniff"를 추가하세요.' },
    es: { title: 'Falta un encabezado menor de tipo de contenido',
      what: "Falta un pequeño encabezado de refuerzo (X-Content-Type-Options). Prioridad muy baja.",
      fix: "Añade \"X-Content-Type-Options: nosniff\" cuando te resulte conveniente." },
    ja: { title: '軽微なコンテンツタイプヘッダーが設定されていません',
      what: '小さな強化用ヘッダー（X-Content-Type-Options）が設定されていません。優先度は非常に低いです。',
      fix: '都合の良いタイミングで「X-Content-Type-Options: nosniff」を追加してください。' },
    pt: { title: 'Falta um cabeçalho menor de tipo de conteúdo',
      what: "Falta um pequeno cabeçalho de reforço (X-Content-Type-Options). Prioridade bem baixa.",
      fix: "Adicione \"X-Content-Type-Options: nosniff\" quando for conveniente." },
    fr: { title: 'Il manque un en-tête mineur de type de contenu',
      what: "Un petit en-tête de renforcement (X-Content-Type-Options) est absent. Priorité très basse.",
      fix: "Ajoutez \"X-Content-Type-Options: nosniff\" quand ce sera pratique." },
    de: { title: 'Ein kleiner Content-Type-Header fehlt',
      what: 'Ein kleiner Härtungs-Header (X-Content-Type-Options) fehlt. Sehr niedrige Priorität.',
      fix: 'Fügen Sie "X-Content-Type-Options: nosniff" hinzu, wenn es zeitlich passt.' },
    zh: { title: '缺少一个次要的内容类型头',
      what: '缺少一个小型加固头(X-Content-Type-Options)。优先级非常低。',
      fix: '有空的时候加上 "X-Content-Type-Options: nosniff" 就行。' },
  },
  no_https_redirect: {
    en: { title: 'Your site can still be opened over an insecure connection',
      what: "Your site answers over plain http:// without sending visitors to the secure https:// version. On shared Wi-Fi, someone nearby can read — or change — what your visitors send and receive.",
      fix: "Turn on \"Force HTTPS\" (sometimes called \"Always use HTTPS\") in your hosting settings so every http:// request redirects to https://." },
    ko: { title: '사이트가 아직 안전하지 않은 연결로도 열립니다',
      what: '사이트가 일반 http:// 로도 응답하며, 안전한 https:// 주소로 보내주지 않습니다. 공용 와이파이에서는 근처의 누군가가 방문자가 주고받는 내용을 읽거나 바꿀 수 있습니다.',
      fix: '호스팅 설정에서 "HTTPS 강제"(Force HTTPS / Always use HTTPS)를 켜서 모든 http:// 요청이 https:// 로 이동하게 하세요.' },
    es: { title: 'Tu sitio todavía se puede abrir por una conexión insegura',
      what: "Tu sitio responde por http:// sin redirigir a los visitantes a la versión segura https://. En una wifi compartida, alguien cerca puede leer —o modificar— lo que tus visitantes envían y reciben.",
      fix: "Activa \"Forzar HTTPS\" (a veces llamado \"Usar siempre HTTPS\") en la configuración de tu hosting para que toda petición http:// redirija a https://." },
    ja: { title: 'サイトが安全でない接続でも開けてしまいます',
      what: 'サイトが通常のhttp://でも応答し、安全なhttps://へ誘導していません。共有Wi-Fiでは、近くにいる第三者が訪問者のやり取りを読んだり書き換えたりできてしまいます。',
      fix: 'ホスティングの設定で「HTTPSを強制」（Force HTTPS / Always use HTTPS）を有効にし、すべてのhttp://リクエストがhttps://へリダイレクトされるようにしてください。' },
    pt: { title: 'Seu site ainda pode ser aberto por uma conexão insegura',
      what: "Seu site responde por http:// sem levar os visitantes para a versão segura https://. Em um wi-fi compartilhado, alguém por perto pode ler — ou alterar — o que seus visitantes enviam e recebem.",
      fix: "Ative \"Forçar HTTPS\" (às vezes chamado de \"Sempre usar HTTPS\") nas configurações da sua hospedagem para que toda requisição http:// redirecione para https://." },
    fr: { title: 'Votre site peut encore être ouvert via une connexion non sécurisée',
      what: "Votre site répond en http:// sans rediriger les visiteurs vers la version sécurisée https://. Sur un wifi partagé, quelqu'un à proximité peut lire — ou modifier — ce que vos visiteurs envoient et reçoivent.",
      fix: "Activez « Forcer HTTPS » (parfois « Toujours utiliser HTTPS ») dans les réglages de votre hébergement pour que chaque requête http:// redirige vers https://." },
    de: { title: 'Ihre Seite lässt sich weiterhin über eine unsichere Verbindung öffnen',
      what: 'Ihre Seite antwortet auch über einfaches http://, ohne Besucher auf die sichere https://-Version zu leiten. In einem geteilten WLAN kann jemand in der Nähe mitlesen — oder verändern —, was Ihre Besucher senden und empfangen.',
      fix: 'Aktivieren Sie in Ihren Hosting-Einstellungen "HTTPS erzwingen" (oft "Always use HTTPS"), damit jede http://-Anfrage auf https:// umgeleitet wird.' },
    zh: { title: '你的网站仍然可以通过不安全的连接打开',
      what: '你的网站通过普通 http:// 也会响应,并没有把访客送到安全的 https:// 版本。在共用 Wi-Fi 下,旁边的人可以读取——甚至篡改——访客收发的内容。',
      fix: '在主机设置中开启"强制 HTTPS"(Force HTTPS / Always use HTTPS),让所有 http:// 请求都跳转到 https://。' },
  },
  hdr_referrer_policy: {
    en: { title: 'Your page addresses can leak to other sites',
      what: "Without a Referrer-Policy, when a visitor clicks a link out of your app, the full address of the page they were on is handed to the other site — which can include addresses you would rather keep private.",
      fix: "Add this header in your hosting settings: Referrer-Policy: strict-origin-when-cross-origin" },
    ko: { title: '페이지 주소가 다른 사이트로 새어나갈 수 있습니다',
      what: 'Referrer-Policy가 없으면, 방문자가 앱에서 외부 링크를 클릭할 때 보고 있던 페이지의 전체 주소가 상대 사이트에 그대로 전달됩니다. 공개하고 싶지 않은 주소가 포함될 수 있습니다.',
      fix: '호스팅 설정에서 이 헤더를 추가하세요: Referrer-Policy: strict-origin-when-cross-origin' },
    es: { title: 'Las direcciones de tus páginas pueden filtrarse a otros sitios',
      what: "Sin una Referrer-Policy, cuando alguien pulsa un enlace que sale de tu app, la dirección completa de la página en la que estaba se entrega al otro sitio — y puede incluir direcciones que preferirías mantener privadas.",
      fix: "Añade este encabezado en la configuración de tu hosting: Referrer-Policy: strict-origin-when-cross-origin" },
    ja: { title: 'ページのアドレスが他サイトに漏れる可能性があります',
      what: 'Referrer-Policyがないと、訪問者がアプリから外部リンクをクリックしたとき、直前に見ていたページの完全なアドレスが相手サイトに渡されます。公開したくないアドレスが含まれることもあります。',
      fix: 'ホスティングの設定で次のヘッダーを追加してください：Referrer-Policy: strict-origin-when-cross-origin' },
    pt: { title: 'Os endereços das suas páginas podem vazar para outros sites',
      what: "Sem uma Referrer-Policy, quando alguém clica em um link que sai do seu app, o endereço completo da página em que estava é entregue ao outro site — e pode incluir endereços que você preferiria manter privados.",
      fix: "Adicione este cabeçalho nas configurações da sua hospedagem: Referrer-Policy: strict-origin-when-cross-origin" },
    fr: { title: "Les adresses de vos pages peuvent fuiter vers d'autres sites",
      what: "Sans Referrer-Policy, lorsqu'un visiteur clique sur un lien sortant de votre app, l'adresse complète de la page qu'il consultait est transmise à l'autre site — y compris des adresses que vous préféreriez garder privées.",
      fix: "Ajoutez cet en-tête dans les réglages de votre hébergement : Referrer-Policy: strict-origin-when-cross-origin" },
    de: { title: 'Ihre Seitenadressen können an andere Websites gelangen',
      what: 'Ohne Referrer-Policy wird beim Klick auf einen Link aus Ihrer App die vollständige Adresse der zuvor besuchten Seite an die andere Website übergeben — darunter können Adressen sein, die Sie lieber privat halten würden.',
      fix: 'Fügen Sie in Ihren Hosting-Einstellungen diesen Header hinzu: Referrer-Policy: strict-origin-when-cross-origin' },
    zh: { title: '你的页面地址可能泄露给其他网站',
      what: '没有 Referrer-Policy 时,访客从你的应用点击外部链接,他所在页面的完整地址会被交给对方网站——其中可能包含你并不想公开的地址。',
      fix: '在主机设置中添加这个头:Referrer-Policy: strict-origin-when-cross-origin' },
  },
  hdr_permissions_policy: {
    en: { title: 'Camera, microphone and location access is not restricted',
      what: "Without a Permissions-Policy, anything embedded in your pages (ads, widgets, third-party frames) is allowed to ask visitors for powerful browser features like camera, microphone or location.",
      fix: "If you don't use those features, switch them off with this header: Permissions-Policy: geolocation=(), microphone=(), camera=()" },
    ko: { title: '카메라·마이크·위치 권한이 제한돼 있지 않습니다',
      what: 'Permissions-Policy가 없으면, 페이지에 삽입된 요소(광고·위젯·외부 프레임 등)가 방문자에게 카메라·마이크·위치 같은 민감한 브라우저 기능을 요청할 수 있습니다.',
      fix: '해당 기능을 쓰지 않는다면 이 헤더로 꺼두세요: Permissions-Policy: geolocation=(), microphone=(), camera=()' },
    es: { title: 'El acceso a cámara, micrófono y ubicación no está restringido',
      what: "Sin una Permissions-Policy, cualquier cosa incrustada en tus páginas (anuncios, widgets, marcos de terceros) puede pedir a los visitantes funciones potentes del navegador como cámara, micrófono o ubicación.",
      fix: "Si no usas esas funciones, desactívalas con este encabezado: Permissions-Policy: geolocation=(), microphone=(), camera=()" },
    ja: { title: 'カメラ・マイク・位置情報の利用が制限されていません',
      what: 'Permissions-Policyがないと、ページに埋め込まれた要素（広告・ウィジェット・外部フレームなど）が、カメラ・マイク・位置情報といった強力なブラウザ機能を訪問者に要求できてしまいます。',
      fix: 'これらの機能を使わないなら、次のヘッダーで無効化してください：Permissions-Policy: geolocation=(), microphone=(), camera=()' },
    pt: { title: 'O acesso a câmera, microfone e localização não está restrito',
      what: "Sem uma Permissions-Policy, qualquer coisa incorporada nas suas páginas (anúncios, widgets, frames de terceiros) pode pedir aos visitantes recursos poderosos do navegador, como câmera, microfone ou localização.",
      fix: "Se você não usa esses recursos, desligue-os com este cabeçalho: Permissions-Policy: geolocation=(), microphone=(), camera=()" },
    fr: { title: "L'accès à la caméra, au micro et à la position n'est pas restreint",
      what: "Sans Permissions-Policy, tout ce qui est intégré dans vos pages (publicités, widgets, cadres tiers) peut demander aux visiteurs des fonctions sensibles du navigateur comme la caméra, le micro ou la position.",
      fix: "Si vous n'utilisez pas ces fonctions, désactivez-les avec cet en-tête : Permissions-Policy: geolocation=(), microphone=(), camera=()" },
    de: { title: 'Zugriff auf Kamera, Mikrofon und Standort ist nicht eingeschränkt',
      what: 'Ohne Permissions-Policy darf alles, was in Ihren Seiten eingebettet ist (Werbung, Widgets, fremde Frames), Besucher nach mächtigen Browser-Funktionen wie Kamera, Mikrofon oder Standort fragen.',
      fix: 'Wenn Sie diese Funktionen nicht nutzen, schalten Sie sie mit diesem Header ab: Permissions-Policy: geolocation=(), microphone=(), camera=()' },
    zh: { title: '摄像头、麦克风和位置权限没有受到限制',
      what: '没有 Permissions-Policy 时,页面里嵌入的任何内容(广告、挂件、第三方框架)都可以向访客索要摄像头、麦克风、位置这类敏感的浏览器功能。',
      fix: '如果你并不使用这些功能,用这个头把它们关掉:Permissions-Policy: geolocation=(), microphone=(), camera=()' },
  },
  info_stack_disclosure: {
    en: { title: 'Your server names the technology you build on',
      what: "Your responses include headers naming your host and framework. This is not a hole on its own — it just makes it slightly quicker for someone to look up known weaknesses for that stack. Most sites live with it.",
      fix: "Optional tidy-up: remove or blank the Server and X-Powered-By headers in your hosting settings. Many platforms don't let you change these, and that's fine — treat this as lowest priority." },
    ko: { title: '서버가 사용 중인 기술을 알려줍니다',
      what: '응답 헤더에 호스팅·프레임워크 이름이 드러납니다. 그 자체로 구멍은 아니고, 해당 기술의 알려진 취약점을 찾아보기 조금 빨라지는 정도입니다. 대부분의 사이트는 그냥 두고 씁니다.',
      fix: '선택적 정리: 호스팅 설정에서 Server·X-Powered-By 헤더를 제거하거나 비우세요. 플랫폼에 따라 아예 못 바꾸는 경우도 많은데 괜찮습니다 — 가장 낮은 우선순위로 두세요.' },
    es: { title: 'Tu servidor revela la tecnología que usas',
      what: "Tus respuestas incluyen encabezados que nombran tu hosting y tu framework. No es un agujero por sí solo — solo hace un poco más rápido buscar debilidades conocidas de esa tecnología. La mayoría de los sitios lo dejan así.",
      fix: "Ajuste opcional: elimina o vacía los encabezados Server y X-Powered-By en la configuración de tu hosting. Muchas plataformas no permiten cambiarlos, y no pasa nada — dale la prioridad más baja." },
    ja: { title: 'サーバーが使用技術を明かしています',
      what: '応答ヘッダーにホスティングやフレームワークの名前が出ています。それ自体が穴ではなく、その技術の既知の弱点を調べるのがわずかに早くなる程度です。多くのサイトはそのままにしています。',
      fix: '任意の整理：ホスティングの設定でServerとX-Powered-Byヘッダーを削除するか空にしてください。変更できないプラットフォームも多く、それで問題ありません — 優先度は最も低く扱ってください。' },
    pt: { title: 'Seu servidor informa a tecnologia que você usa',
      what: "Suas respostas incluem cabeçalhos com o nome da sua hospedagem e do seu framework. Isso não é uma falha por si só — apenas deixa um pouco mais rápido procurar fraquezas conhecidas dessa tecnologia. A maioria dos sites convive com isso.",
      fix: "Ajuste opcional: remova ou esvazie os cabeçalhos Server e X-Powered-By nas configurações da hospedagem. Muitas plataformas não deixam alterar isso, e tudo bem — trate como a menor prioridade." },
    fr: { title: 'Votre serveur annonce la technologie que vous utilisez',
      what: "Vos réponses contiennent des en-têtes qui nomment votre hébergement et votre framework. Ce n'est pas une faille en soi — cela rend juste un peu plus rapide la recherche de failles connues pour cette technologie. La plupart des sites vivent très bien avec.",
      fix: "Réglage facultatif : supprimez ou videz les en-têtes Server et X-Powered-By dans les réglages de votre hébergement. Beaucoup de plateformes ne le permettent pas, et ce n'est pas grave — priorité la plus basse." },
    de: { title: 'Ihr Server nennt die eingesetzte Technologie',
      what: 'Ihre Antworten enthalten Header, die Hosting und Framework benennen. Das ist für sich genommen keine Lücke — es macht es nur etwas schneller, bekannte Schwachstellen dieser Technik nachzuschlagen. Die meisten Seiten leben damit.',
      fix: 'Optionale Aufräumarbeit: Entfernen oder leeren Sie die Header Server und X-Powered-By in Ihren Hosting-Einstellungen. Viele Plattformen lassen das gar nicht zu — das ist in Ordnung, niedrigste Priorität.' },
    zh: { title: '你的服务器暴露了所用的技术',
      what: '响应头里写明了你的托管平台和框架。这本身不是漏洞——只是让别人查这套技术的已知弱点稍微快一点。大多数网站都不管它。',
      fix: '可选整理:在主机设置中删除或清空 Server 和 X-Powered-By 头。很多平台根本不允许改,这也没关系——把它当作优先级最低的一项。' },
  },
  csp_weak: {
    en: { title: 'Your script protection has a hole in it',
      what: "You do have a Content-Security-Policy, but it still allows inline or dynamically-built scripts. That is the exact thing a CSP is meant to stop, so an injected script could still run.",
      fix: "In your CSP, remove 'unsafe-inline' and 'unsafe-eval' (and any bare *). If a library needs inline scripts, use a nonce or hash instead." },
    ko: { title: '스크립트 보호에 구멍이 있습니다',
      what: 'Content-Security-Policy가 있긴 하지만, 인라인 스크립트나 즉석에서 만들어지는 스크립트를 여전히 허용합니다. CSP가 막으려던 게 바로 그것이라, 주입된 악성 스크립트가 그대로 실행될 수 있습니다.',
      fix: "CSP에서 'unsafe-inline'과 'unsafe-eval'(그리고 그냥 *)을 빼세요. 인라인 스크립트가 꼭 필요한 라이브러리가 있으면 nonce나 해시를 쓰세요." },
    es: { title: 'Tu protección de scripts tiene un agujero',
      what: "Sí tienes una Content-Security-Policy, pero todavía permite scripts en línea o generados sobre la marcha. Eso es justo lo que una CSP debería impedir, así que un script inyectado aún podría ejecutarse.",
      fix: "En tu CSP, quita 'unsafe-inline' y 'unsafe-eval' (y cualquier * suelto). Si alguna librería necesita scripts en línea, usa un nonce o un hash." },
    ja: { title: 'スクリプト保護に穴があります',
      what: 'Content-Security-Policyは設定されていますが、インラインスクリプトや動的に生成されるスクリプトを依然として許可しています。それこそCSPが防ぐべきものなので、注入されたスクリプトが実行されてしまう可能性があります。',
      fix: "CSPから'unsafe-inline'と'unsafe-eval'（および裸の*）を外してください。インラインスクリプトが必要なライブラリがある場合は、nonceかハッシュを使ってください。" },
    pt: { title: 'Sua proteção contra scripts tem um furo',
      what: "Você tem uma Content-Security-Policy, mas ela ainda permite scripts inline ou criados dinamicamente. É exatamente isso que uma CSP deveria impedir, então um script injetado ainda poderia rodar.",
      fix: "Na sua CSP, remova 'unsafe-inline' e 'unsafe-eval' (e qualquer * solto). Se alguma biblioteca precisa de scripts inline, use um nonce ou hash." },
    fr: { title: 'Votre protection contre les scripts a une faille',
      what: "Vous avez bien une Content-Security-Policy, mais elle autorise encore les scripts en ligne ou générés à la volée. C'est précisément ce qu'une CSP doit empêcher : un script injecté pourrait donc s'exécuter.",
      fix: "Dans votre CSP, retirez 'unsafe-inline' et 'unsafe-eval' (ainsi que tout * isolé). Si une bibliothèque exige des scripts en ligne, utilisez un nonce ou un hash." },
    de: { title: 'Ihr Skript-Schutz hat ein Loch',
      what: 'Sie haben zwar eine Content-Security-Policy, sie erlaubt aber weiterhin Inline-Skripte oder dynamisch erzeugten Code. Genau das soll eine CSP verhindern — ein eingeschleustes Skript könnte also trotzdem laufen.',
      fix: "Entfernen Sie in Ihrer CSP 'unsafe-inline' und 'unsafe-eval' (sowie ein alleinstehendes *). Falls eine Bibliothek Inline-Skripte braucht, nutzen Sie stattdessen einen Nonce oder Hash." },
    zh: { title: '你的脚本防护有个漏洞',
      what: '你确实设置了 Content-Security-Policy,但它仍然允许内联脚本或动态生成的脚本。而这正是 CSP 本该拦住的东西,所以被注入的脚本依然可能执行。',
      fix: "在 CSP 中去掉 'unsafe-inline' 和 'unsafe-eval'(以及单独的 *)。如果某个库必须用内联脚本,改用 nonce 或哈希。" },
  },
  hsts_short: {
    en: { title: 'Your HTTPS enforcement expires too soon',
      what: "You send an HSTS header, but with a short lifetime. Browsers forget the rule quickly, so a visitor returning after it expires can still be pushed onto an insecure connection.",
      fix: "Raise it to at least six months: Strict-Transport-Security: max-age=31536000; includeSubDomains" },
    ko: { title: 'HTTPS 강제 설정이 너무 빨리 만료됩니다',
      what: 'HSTS 헤더를 보내고는 있지만 유효기간이 짧습니다. 브라우저가 금방 잊어버리기 때문에, 만료 후 다시 방문한 사람은 여전히 안전하지 않은 연결로 유도될 수 있습니다.',
      fix: '최소 6개월 이상으로 올리세요: Strict-Transport-Security: max-age=31536000; includeSubDomains' },
    es: { title: 'Tu refuerzo de HTTPS caduca demasiado pronto',
      what: "Envías un encabezado HSTS, pero con una duración corta. Los navegadores olvidan la regla rápido, así que un visitante que vuelva tras la caducidad aún puede acabar en una conexión insegura.",
      fix: "Súbelo a seis meses como mínimo: Strict-Transport-Security: max-age=31536000; includeSubDomains" },
    ja: { title: 'HTTPS強制の有効期限が短すぎます',
      what: 'HSTSヘッダーは送っていますが、有効期間が短すぎます。ブラウザはすぐにその指示を忘れるため、期限切れ後に再訪した人は依然として安全でない接続に誘導されうります。',
      fix: '最低6か月以上に引き上げてください：Strict-Transport-Security: max-age=31536000; includeSubDomains' },
    pt: { title: 'Sua imposição de HTTPS expira cedo demais',
      what: "Você envia um cabeçalho HSTS, mas com validade curta. Os navegadores esquecem a regra rápido, então quem voltar depois do vencimento ainda pode ser levado a uma conexão insegura.",
      fix: "Aumente para pelo menos seis meses: Strict-Transport-Security: max-age=31536000; includeSubDomains" },
    fr: { title: 'Votre obligation HTTPS expire trop vite',
      what: "Vous envoyez bien un en-tête HSTS, mais avec une durée courte. Les navigateurs oublient vite la règle : un visiteur qui revient après expiration peut encore être basculé sur une connexion non sécurisée.",
      fix: "Passez à six mois minimum : Strict-Transport-Security: max-age=31536000; includeSubDomains" },
    de: { title: 'Ihre HTTPS-Erzwingung läuft zu früh ab',
      what: 'Sie senden zwar einen HSTS-Header, aber mit kurzer Gültigkeit. Browser vergessen die Regel schnell — wer nach Ablauf zurückkehrt, kann weiterhin auf eine unsichere Verbindung geleitet werden.',
      fix: 'Erhöhen Sie auf mindestens sechs Monate: Strict-Transport-Security: max-age=31536000; includeSubDomains' },
    zh: { title: '你的 HTTPS 强制策略过期太快',
      what: '你确实发送了 HSTS 头,但有效期很短。浏览器很快就会忘记这条规则,过期后再访问的用户仍可能被引导到不安全的连接上。',
      fix: '把有效期提到至少半年:Strict-Transport-Security: max-age=31536000; includeSubDomains' },
  },
  cookie_insecure: {
    en: { title: 'Your cookies are missing basic protections',
      what: "A cookie is being set without the flags that keep it safe. Depending on which are missing, it can travel over insecure connections, be read by scripts on the page, or be sent along by other sites — which is how session hijacking usually starts.",
      fix: "Set every cookie with: Secure; HttpOnly; SameSite=Lax (use SameSite=None only when a cookie genuinely must work cross-site, and then always with Secure)." },
    ko: { title: '쿠키에 기본 보호 설정이 빠져 있습니다',
      what: '쿠키가 안전장치 없이 설정되고 있습니다. 빠진 항목에 따라 안전하지 않은 연결로 오가거나, 페이지의 스크립트가 읽어가거나, 다른 사이트 요청에 딸려 나갈 수 있습니다. 세션 탈취는 보통 여기서 시작됩니다.',
      fix: '모든 쿠키에 다음을 설정하세요: Secure; HttpOnly; SameSite=Lax (교차 사이트에서 꼭 필요한 쿠키만 SameSite=None을 쓰고, 그때는 반드시 Secure와 함께 쓰세요.)' },
    es: { title: 'A tus cookies les faltan protecciones básicas',
      what: "Se está creando una cookie sin las marcas que la mantienen a salvo. Según cuáles falten, puede viajar por conexiones inseguras, ser leída por scripts de la página o enviarse desde otros sitios — así suele empezar el robo de sesión.",
      fix: "Crea todas las cookies con: Secure; HttpOnly; SameSite=Lax (usa SameSite=None solo si de verdad debe funcionar entre sitios, y siempre junto a Secure)." },
    ja: { title: 'Cookieに基本的な保護設定が欠けています',
      what: 'Cookieが安全のためのフラグなしで設定されています。欠けている項目によっては、安全でない接続を通ったり、ページ上のスクリプトから読まれたり、他サイトからの要求に付いて送られたりします。セッション乗っ取りはたいていここから始まります。',
      fix: 'すべてのCookieに次を設定してください：Secure; HttpOnly; SameSite=Lax（クロスサイトで本当に必要なCookieのみSameSite=Noneを使い、その場合は必ずSecureと併用してください）' },
    pt: { title: 'Seus cookies estão sem proteções básicas',
      what: "Um cookie está sendo definido sem as flags que o mantêm seguro. Dependendo de quais faltam, ele pode trafegar por conexões inseguras, ser lido por scripts da página ou ser enviado a partir de outros sites — é assim que costuma começar o roubo de sessão.",
      fix: "Defina todos os cookies com: Secure; HttpOnly; SameSite=Lax (use SameSite=None só quando o cookie realmente precisar funcionar entre sites, e sempre junto com Secure)." },
    fr: { title: 'Vos cookies n’ont pas les protections de base',
      what: "Un cookie est défini sans les attributs qui le protègent. Selon ceux qui manquent, il peut circuler sur des connexions non sécurisées, être lu par les scripts de la page, ou être envoyé depuis d'autres sites — c'est ainsi que commence en général le vol de session.",
      fix: "Définissez chaque cookie avec : Secure; HttpOnly; SameSite=Lax (n'utilisez SameSite=None que si le cookie doit vraiment fonctionner entre sites, et toujours avec Secure)." },
    de: { title: 'Ihren Cookies fehlen grundlegende Schutzmaßnahmen',
      what: 'Ein Cookie wird ohne die schützenden Flags gesetzt. Je nachdem, welche fehlen, kann es über unsichere Verbindungen laufen, von Skripten auf der Seite gelesen oder von anderen Websites mitgeschickt werden — so beginnt typischerweise Session-Hijacking.',
      fix: 'Setzen Sie jedes Cookie mit: Secure; HttpOnly; SameSite=Lax (SameSite=None nur, wenn ein Cookie wirklich seitenübergreifend funktionieren muss — dann immer zusammen mit Secure).' },
    zh: { title: '你的 Cookie 缺少基本保护',
      what: 'Cookie 在设置时没有加上保护它的标记。取决于缺了哪些,它可能通过不安全的连接传输、被页面上的脚本读取,或者被其他网站的请求顺带发送——会话劫持通常就是这么开始的。',
      fix: '给所有 Cookie 都加上:Secure; HttpOnly; SameSite=Lax(只有确实需要跨站生效的 Cookie 才用 SameSite=None,而且必须同时加 Secure)。' },
  },
  insecure_form_action: {
    en: { title: 'A form on your page sends data unencrypted',
      what: "One of your forms submits to an http:// address. Whatever a visitor types into it — including a password — travels in the clear and can be read or altered by anyone on the same network, even though your page itself loaded securely.",
      fix: "Change the form's action to the https:// version of the same address." },
    ko: { title: '페이지의 폼이 암호화 없이 데이터를 전송합니다',
      what: '폼 중 하나가 http:// 주소로 전송됩니다. 방문자가 거기에 입력한 내용은 — 비밀번호를 포함해 — 평문으로 오가기 때문에, 페이지 자체는 안전하게 열렸더라도 같은 네트워크에 있는 누군가가 읽거나 바꿀 수 있습니다.',
      fix: '폼의 action을 같은 주소의 https:// 버전으로 바꾸세요.' },
    es: { title: 'Un formulario de tu página envía datos sin cifrar',
      what: "Uno de tus formularios se envía a una dirección http://. Todo lo que alguien escriba ahí —incluida una contraseña— viaja en claro y puede ser leído o modificado por cualquiera en la misma red, aunque tu página se haya cargado de forma segura.",
      fix: "Cambia el action del formulario a la versión https:// de esa misma dirección." },
    ja: { title: 'ページ上のフォームがデータを暗号化せずに送信しています',
      what: 'フォームの1つがhttp://のアドレスに送信しています。そこに入力された内容は——パスワードを含めて——平文で流れるため、ページ自体は安全に読み込まれていても、同じネットワーク上の誰かに読まれたり書き換えられたりします。',
      fix: 'フォームのactionを、同じアドレスのhttps://版に変更してください。' },
    pt: { title: 'Um formulário da sua página envia dados sem criptografia',
      what: "Um dos seus formulários envia para um endereço http://. Tudo o que a pessoa digitar nele — inclusive uma senha — trafega em texto puro e pode ser lido ou alterado por qualquer um na mesma rede, mesmo que sua página tenha carregado de forma segura.",
      fix: "Troque o action do formulário para a versão https:// do mesmo endereço." },
    fr: { title: 'Un formulaire de votre page envoie les données en clair',
      what: "L'un de vos formulaires est envoyé vers une adresse http://. Tout ce qu'un visiteur y saisit — mot de passe compris — circule en clair et peut être lu ou modifié par quiconque sur le même réseau, même si votre page s'est chargée de façon sécurisée.",
      fix: "Remplacez l'action du formulaire par la version https:// de la même adresse." },
    de: { title: 'Ein Formular auf Ihrer Seite sendet Daten unverschlüsselt',
      what: 'Eines Ihrer Formulare sendet an eine http://-Adresse. Alles, was jemand dort eingibt — auch Passwörter — läuft im Klartext und kann von jedem im selben Netzwerk mitgelesen oder verändert werden, selbst wenn Ihre Seite sicher geladen wurde.',
      fix: 'Ändern Sie das action-Ziel des Formulars auf die https://-Variante derselben Adresse.' },
    zh: { title: '页面上的表单在未加密的情况下发送数据',
      what: '你的某个表单提交到了 http:// 地址。访客在里面输入的一切——包括密码——都是明文传输,即使页面本身是安全加载的,同一网络里的任何人都可能读取甚至篡改。',
      fix: '把表单的 action 改成同一地址的 https:// 版本。' },
  },
  exposed_backup: {
    en: { title: 'A database backup can be downloaded from your site',
      what: "A database dump or backup file is publicly downloadable. These usually contain every row you have — accounts, emails, orders — so this is the most direct kind of data breach there is.",
      fix: "Delete it from your public/deploy folder right now. Then assume its contents are already public: reset passwords and rotate any keys it contained." },
    ko: { title: '사이트에서 데이터베이스 백업을 내려받을 수 있습니다',
      what: '데이터베이스 덤프나 백업 파일을 누구나 내려받을 수 있습니다. 이런 파일에는 보통 모든 데이터가 들어 있습니다 — 계정, 이메일, 주문 내역까지. 가장 직접적인 형태의 데이터 유출입니다.',
      fix: '지금 즉시 공개/배포 폴더에서 삭제하세요. 그리고 내용이 이미 공개된 것으로 간주하고, 비밀번호를 재설정하고 안에 있던 키는 전부 재발급하세요.' },
    es: { title: 'Se puede descargar una copia de tu base de datos desde tu sitio',
      what: "Un volcado o copia de seguridad de la base de datos se puede descargar públicamente. Suelen contener todos tus registros —cuentas, correos, pedidos—, así que es la forma más directa de filtración de datos que existe.",
      fix: "Bórralo ya de tu carpeta pública/de despliegue. Después da por hecho que su contenido ya es público: restablece contraseñas y renueva todas las claves que contuviera." },
    ja: { title: 'サイトからデータベースのバックアップをダウンロードできます',
      what: 'データベースのダンプやバックアップファイルが誰でもダウンロードできる状態です。この種のファイルには通常すべてのデータ——アカウント、メールアドレス、注文履歴まで——が含まれます。最も直接的な情報漏えいです。',
      fix: '今すぐ公開/デプロイ用フォルダから削除してください。そのうえで中身はすでに公開されたものとみなし、パスワードをリセットし、含まれていたキーはすべて再発行してください。' },
    pt: { title: 'Um backup do banco de dados pode ser baixado do seu site',
      what: "Um dump ou arquivo de backup do banco está publicamente disponível para download. Normalmente esses arquivos contêm todos os seus registros — contas, e-mails, pedidos —, então esse é o tipo mais direto de vazamento de dados que existe.",
      fix: "Apague agora da sua pasta pública/de deploy. Depois, considere que o conteúdo já é público: redefina senhas e gere novas chaves para tudo que estava ali." },
    fr: { title: 'Une sauvegarde de base de données est téléchargeable depuis votre site',
      what: "Un export ou une sauvegarde de base de données est téléchargeable publiquement. Ces fichiers contiennent en général toutes vos données — comptes, e-mails, commandes : c'est la forme la plus directe de fuite de données.",
      fix: "Supprimez-le immédiatement de votre dossier public/de déploiement. Considérez ensuite son contenu comme déjà public : réinitialisez les mots de passe et régénérez toutes les clés qu'il contenait." },
    de: { title: 'Ein Datenbank-Backup lässt sich von Ihrer Seite herunterladen',
      what: 'Ein Datenbank-Dump oder Backup ist öffentlich herunterladbar. Solche Dateien enthalten meist sämtliche Datensätze — Konten, E-Mail-Adressen, Bestellungen. Das ist die direkteste Form eines Datenlecks.',
      fix: 'Löschen Sie die Datei sofort aus Ihrem öffentlichen/Deploy-Ordner. Gehen Sie danach davon aus, dass der Inhalt bereits öffentlich ist: Passwörter zurücksetzen und alle enthaltenen Schlüssel neu erzeugen.' },
    zh: { title: '别人可以从你的网站下载数据库备份',
      what: '数据库导出或备份文件可以被公开下载。这类文件通常包含你的全部数据——账号、邮箱、订单记录。这是最直接的一种数据泄露。',
      fix: '立刻从公开/部署目录中删除它。然后就当里面的内容已经公开了:重置密码,并把里面出现过的密钥全部更换。' },
  },
  google_api_key_client: {
    en: { title: 'A Google API key is in your app — make sure it’s restricted',
      what: "Google/Firebase web keys are meant to be public, but if left unrestricted they can be abused for quota or billing.",
      fix: "In Google Cloud Console, restrict the key to your own website/domain and to only the APIs it needs." },
    ko: { title: 'Google API 키가 앱에 있습니다 — 제한 설정을 확인하세요',
      what: 'Google/Firebase 웹 키는 공개돼도 되지만, 제한이 없으면 할당량·요금 악용에 쓰일 수 있습니다.',
      fix: 'Google Cloud Console에서 키를 당신 웹사이트/도메인과 필요한 API로만 제한하세요.' },
    es: { title: 'Hay una clave de API de Google en tu app — asegúrate de que esté restringida',
      what: "Las claves web de Google/Firebase están pensadas para ser públicas, pero si no tienen restricciones pueden usarse indebidamente para abusar de la cuota o generar cargos.",
      fix: "En Google Cloud Console, restringe la clave a tu propio sitio web/dominio y solo a las API que necesita." },
    ja: { title: 'GoogleのAPIキーがアプリ内にあります — 制限設定を確認してください',
      what: 'Google/FirebaseのウェブキーはPublicになる前提のものですが、制限をかけていないと、割り当てや料金を悪用される可能性があります。',
      fix: 'Google Cloud Consoleで、キーを自分のウェブサイト/ドメインと必要なAPIのみに制限してください。' },
    pt: { title: 'Uma chave de API do Google está no seu app — confira se ela tem restrições',
      what: "Chaves web do Google/Firebase são feitas para serem públicas, mas se ficarem sem restrição podem ser usadas indevidamente para gastar sua cota ou gerar cobranças.",
      fix: "No Google Cloud Console, restrinja a chave ao seu próprio site/domínio e apenas às APIs que ela realmente precisa usar." },
    fr: { title: "Une clé API Google est présente dans votre app — vérifiez qu'elle est restreinte",
      what: "Les clés web Google/Firebase sont censées être publiques, mais si elles ne sont pas restreintes, elles peuvent être détournées pour consommer votre quota ou générer des frais.",
      fix: "Dans Google Cloud Console, limitez la clé à votre propre site/domaine et uniquement aux API dont elle a besoin." },
    de: { title: 'Ein Google-API-Schlüssel ist in Ihrer App — stellen Sie sicher, dass er eingeschränkt ist',
      what: 'Google/Firebase-Web-Schlüssel sind zum öffentlichen Gebrauch gedacht, aber ohne Einschränkung können sie für Kontingent- oder Kostenmissbrauch ausgenutzt werden.',
      fix: 'Beschränken Sie den Schlüssel in der Google Cloud Console auf Ihre eigene Website/Domain und nur auf die benötigten APIs.' },
    zh: { title: '应用中有 Google API 密钥——确认它已经加了限制',
      what: 'Google/Firebase 的 Web 密钥本来就是公开的,但如果不加限制,可能被人滥用来消耗配额或产生费用。',
      fix: '在 Google Cloud Console 里把这个密钥限制为只能用于你自己的网站/域名,并且只允许它需要的那些 API。' },
  },
  exposed_sourcemap: {
    en: { title: 'Your original source code is viewable (source maps)',
      what: "Source maps let anyone read your original, un-minified code. Minor, but you may not want it public.",
      fix: "Disable source maps in your production build settings." },
    ko: { title: '원본 소스코드가 보입니다(소스맵)',
      what: '소스맵은 원본 코드를 그대로 읽을 수 있게 합니다. 사소하지만 공개를 원치 않을 수 있습니다.',
      fix: '프로덕션 빌드 설정에서 소스맵을 끄세요.' },
    es: { title: 'Tu código fuente original es visible (source maps)',
      what: "Los source maps permiten que cualquiera lea tu código original, sin minificar. Es un riesgo menor, pero quizás no quieras que sea público.",
      fix: "Desactiva los source maps en la configuración de tu build de producción." },
    ja: { title: '元のソースコードが閲覧可能です（source maps）',
      what: 'source mapsがあると、誰でも圧縮前の元のコードを読み取れてしまいます。軽微な問題ですが、公開したくない場合もあるでしょう。',
      fix: '本番ビルドの設定でsource mapsを無効にしてください。' },
    pt: { title: 'Seu código-fonte original pode ser visto (source maps)',
      what: "Os source maps permitem que qualquer pessoa leia seu código original, sem minificação. É um risco pequeno, mas você pode não querer isso público.",
      fix: "Desative os source maps nas configurações de build de produção." },
    fr: { title: 'Votre code source original est consultable (source maps)',
      what: "Les source maps permettent à n'importe qui de lire votre code original, non minifié. C'est mineur, mais vous ne voulez peut-être pas que ce soit public.",
      fix: "Désactivez les source maps dans les paramètres de build de production." },
    de: { title: 'Ihr ursprünglicher Quellcode ist einsehbar (Source Maps)',
      what: 'Source Maps lassen jeden Ihren originalen, nicht minifizierten Code lesen. Geringfügig, aber Sie wollen das vielleicht nicht öffentlich.',
      fix: 'Deaktivieren Sie Source Maps in Ihren Produktions-Build-Einstellungen.' },
    zh: { title: '原始源代码可以被查看(source map)',
      what: 'source map 让任何人都能读到你未压缩的原始代码。问题不大,但你可能不希望它公开。',
      fix: '在你的生产环境构建设置里关闭 source map。' },
  },
  // ---- added 2026-07-25: AI-stack / dev-tool key coverage expansion ----
  github_token: {
    en: { title: 'A GitHub access token is exposed',
      what: "A GitHub personal access token is visible in your app. Anyone who finds it can access your repositories — and depending on its scope, push code, read private repos, or manage your account.",
      fix: "Revoke the token in GitHub → Settings → Developer settings → Personal access tokens, then generate a new one and keep it on the server only." },
    ko: { title: 'GitHub 액세스 토큰이 노출됐습니다',
      what: '앱에 GitHub 개인 액세스 토큰이 보입니다. 발견한 사람은 권한 범위에 따라 저장소에 접근하거나, 코드를 푸시하거나, 비공개 저장소를 읽거나, 계정을 관리할 수 있습니다.',
      fix: 'GitHub → Settings → Developer settings → Personal access tokens에서 토큰을 폐기하고 새로 발급해 서버에만 두세요.' },
    es: { title: 'Un token de acceso de GitHub está expuesto',
      what: "Un token de acceso personal de GitHub es visible en tu app. Cualquiera que lo encuentre puede acceder a tus repositorios — y, según su alcance (scope), subir código (push), leer repositorios privados o administrar tu cuenta.",
      fix: "Revoca el token en GitHub → Settings → Developer settings → Personal access tokens, luego genera uno nuevo y consérvalo solo en el servidor." },
    ja: { title: 'GitHubのアクセストークンが漏えいしています',
      what: 'アプリ内にGitHubのパーソナルアクセストークンが見えています。見つけた人は誰でもあなたのリポジトリにアクセスでき、スコープによってはコードのプッシュ、非公開リポジトリの閲覧、アカウントの管理までできてしまいます。',
      fix: 'GitHubの Settings → Developer settings → Personal access tokens でトークンを無効化し、新しいトークンを発行してサーバー側だけに保管してください。' },
    pt: { title: 'Um token de acesso do GitHub está exposto',
      what: "Um token de acesso pessoal do GitHub está visível no seu app. Quem encontrar esse token pode acessar seus repositórios — e, dependendo do escopo, enviar código (push), ler repositórios privados ou gerenciar sua conta.",
      fix: "Revogue o token em GitHub → Settings → Developer settings → Personal access tokens, gere um novo e mantenha-o apenas no servidor." },
    fr: { title: 'Un token d\'accès GitHub est exposé',
      what: "Un token d'accès personnel GitHub est visible dans votre app. Toute personne qui le trouve peut accéder à vos dépôts — et selon sa portée, pousser du code, lire des dépôts privés ou gérer votre compte.",
      fix: "Révoquez le token dans GitHub → Settings → Developer settings → Personal access tokens, puis générez-en un nouveau et gardez-le uniquement sur le serveur." },
    de: { title: 'Ein GitHub-Zugriffstoken ist offengelegt',
      what: 'Ein persönliches GitHub-Zugriffstoken ist in Ihrer App sichtbar. Wer es findet, kann je nach Berechtigungsumfang auf Ihre Repositories zugreifen, Code pushen, private Repositories lesen oder Ihr Konto verwalten.',
      fix: 'Widerrufen Sie das Token unter GitHub → Settings → Developer settings → Personal access tokens, erstellen Sie ein neues und bewahren Sie es nur auf dem Server auf.' },
    zh: { title: 'GitHub 访问令牌泄露了',
      what: '应用中暴露了一个 GitHub 个人访问令牌。发现它的人可以访问你的仓库——根据权限范围,还能推送代码、读取私有仓库,甚至管理你的账户。',
      fix: '在 GitHub → Settings → Developer settings → Personal access tokens 中撤销该令牌,重新生成一个新的,只保存在服务器端。' },
  },
  slack_token: {
    en: { title: 'A Slack token is exposed',
      what: "A Slack bot/API token is visible in your app. Anyone who finds it can read messages, post as your bot, or access your workspace depending on its permissions.",
      fix: "Revoke the token in your Slack app's settings (api.slack.com/apps → your app → OAuth & Permissions), then reinstall and keep the new token on the server only." },
    ko: { title: 'Slack 토큰이 노출됐습니다',
      what: '앱에 Slack 봇/API 토큰이 보입니다. 발견한 사람은 권한에 따라 메시지를 읽거나, 봇으로 글을 올리거나, 워크스페이스에 접근할 수 있습니다.',
      fix: 'Slack 앱 설정(api.slack.com/apps → 해당 앱 → OAuth & Permissions)에서 토큰을 폐기하고 재설치한 뒤, 새 토큰은 서버에만 두세요.' },
    es: { title: 'Un token de Slack está expuesto',
      what: "Un token de bot/API de Slack es visible en tu app. Cualquiera que lo encuentre puede leer mensajes, publicar como tu bot o acceder a tu workspace según sus permisos.",
      fix: "Revoca el token en la configuración de tu app de Slack (api.slack.com/apps → tu app → OAuth & Permissions), luego reinstálala y conserva el nuevo token solo en el servidor." },
    ja: { title: 'Slackのトークンが漏えいしています',
      what: 'アプリ内にSlackのボット/APIトークンが見えています。見つけた人は権限次第でメッセージを読んだり、あなたのボットとして投稿したり、ワークスペースにアクセスしたりできてしまいます。',
      fix: 'Slackアプリの設定（api.slack.com/apps → 該当アプリ → OAuth & Permissions）でトークンを無効化し、再インストールしてから新しいトークンをサーバー側だけに保管してください。' },
    pt: { title: 'Um token do Slack está exposto',
      what: "Um token de bot/API do Slack está visível no seu app. Quem encontrar esse token pode ler mensagens, publicar como seu bot ou acessar seu workspace, dependendo das permissões.",
      fix: "Revogue o token nas configurações do seu app do Slack (api.slack.com/apps → seu app → OAuth & Permissions), reinstale e mantenha o novo token apenas no servidor." },
    fr: { title: 'Un token Slack est exposé',
      what: "Un token bot/API Slack est visible dans votre app. Toute personne qui le trouve peut lire des messages, publier en tant que votre bot, ou accéder à votre espace de travail selon ses permissions.",
      fix: "Révoquez le token dans les paramètres de votre app Slack (api.slack.com/apps → votre app → OAuth & Permissions), puis réinstallez-la et gardez le nouveau token uniquement sur le serveur." },
    de: { title: 'Ein Slack-Token ist offengelegt',
      what: 'Ein Slack-Bot-/API-Token ist in Ihrer App sichtbar. Wer es findet, kann je nach Berechtigungen Nachrichten lesen, als Ihr Bot posten oder auf Ihren Workspace zugreifen.',
      fix: 'Widerrufen Sie das Token in den Einstellungen Ihrer Slack-App (api.slack.com/apps → Ihre App → OAuth & Permissions), installieren Sie sie neu und bewahren Sie das neue Token nur auf dem Server auf.' },
    zh: { title: 'Slack 令牌泄露了',
      what: '应用中暴露了一个 Slack 机器人/API 令牌。发现它的人可以根据权限读取消息、以你的机器人身份发帖,或访问你的工作区。',
      fix: '在你的 Slack 应用设置(api.slack.com/apps → 该应用 → OAuth & Permissions)中撤销该令牌,重新安装,新令牌只保存在服务器端。' },
  },
  huggingface_token: {
    en: { title: 'A Hugging Face access token is exposed',
      what: "A Hugging Face token is visible in your app. Anyone who finds it can use your account's model/inference quota, or access private models and datasets depending on its scope.",
      fix: "Revoke the token in Hugging Face → Settings → Access Tokens, generate a new one, and keep it on the server only." },
    ko: { title: 'Hugging Face 액세스 토큰이 노출됐습니다',
      what: '앱에 Hugging Face 토큰이 보입니다. 발견한 사람은 권한 범위에 따라 당신 계정의 모델·추론 할당량을 쓰거나, 비공개 모델·데이터셋에 접근할 수 있습니다.',
      fix: 'Hugging Face → Settings → Access Tokens에서 토큰을 폐기하고 새로 발급해 서버에만 두세요.' },
    es: { title: 'Un token de acceso de Hugging Face está expuesto',
      what: "Un token de Hugging Face es visible en tu app. Cualquiera que lo encuentre puede usar la cuota de modelos/inferencia de tu cuenta, o acceder a modelos y datasets privados según su alcance.",
      fix: "Revoca el token en Hugging Face → Settings → Access Tokens, genera uno nuevo y consérvalo solo en el servidor." },
    ja: { title: 'Hugging Faceのアクセストークンが漏えいしています',
      what: 'アプリ内にHugging Faceのトークンが見えています。見つけた人はスコープに応じて、あなたのアカウントのモデル/推論クォータを使ったり、非公開のモデルやデータセットにアクセスしたりできてしまいます。',
      fix: 'Hugging Faceの Settings → Access Tokens でトークンを無効化し、新しいトークンを発行してサーバー側だけに保管してください。' },
    pt: { title: 'Um token de acesso do Hugging Face está exposto',
      what: "Um token do Hugging Face está visível no seu app. Quem encontrar esse token pode usar a cota de modelos/inferência da sua conta, ou acessar modelos e datasets privados dependendo do escopo.",
      fix: "Revogue o token em Hugging Face → Settings → Access Tokens, gere um novo e mantenha-o apenas no servidor." },
    fr: { title: "Un token d'accès Hugging Face est exposé",
      what: "Un token Hugging Face est visible dans votre app. Toute personne qui le trouve peut utiliser le quota de modèles/inférence de votre compte, ou accéder à des modèles et jeux de données privés selon sa portée.",
      fix: "Révoquez le token dans Hugging Face → Settings → Access Tokens, générez-en un nouveau et gardez-le uniquement sur le serveur." },
    de: { title: 'Ein Hugging-Face-Zugriffstoken ist offengelegt',
      what: 'Ein Hugging-Face-Token ist in Ihrer App sichtbar. Wer es findet, kann je nach Berechtigungsumfang das Modell-/Inferenz-Kontingent Ihres Kontos nutzen oder auf private Modelle und Datensätze zugreifen.',
      fix: 'Widerrufen Sie das Token unter Hugging Face → Settings → Access Tokens, erstellen Sie ein neues und bewahren Sie es nur auf dem Server auf.' },
    zh: { title: 'Hugging Face 访问令牌泄露了',
      what: '应用中暴露了一个 Hugging Face 令牌。发现它的人可以根据权限范围占用你账户的模型/推理额度,或访问私有模型和数据集。',
      fix: '在 Hugging Face → Settings → Access Tokens 中撤销该令牌,重新生成一个新的,只保存在服务器端。' },
  },
  groq_key: {
    en: { title: 'A Groq API key is exposed',
      what: "A Groq key is visible in your app. Anyone who finds it can run up usage charges on your account.",
      fix: "Revoke the key in your Groq console and create a new one, kept on the server only." },
    ko: { title: 'Groq API 키가 노출됐습니다',
      what: '앱에 Groq 키가 보입니다. 누구나 복사해 당신 계정으로 사용 요금을 발생시킬 수 있습니다.',
      fix: 'Groq 콘솔에서 키를 폐기하고 새 키를 발급해 서버에만 두세요.' },
    es: { title: 'Tu clave de API de Groq está expuesta',
      what: "Una clave de Groq es visible en tu app. Cualquiera que la encuentre puede generar cargos de uso en tu cuenta.",
      fix: "Revoca la clave en tu consola de Groq y crea una nueva, manteniéndola solo en el servidor." },
    ja: { title: 'GroqのAPIキーが漏えいしています',
      what: 'アプリ内にGroqのキーが見えています。見つけた人は誰でも、あなたのアカウントに利用料金を発生させることができます。',
      fix: 'Groqのコンソールでキーを無効化し、新しいキーを作成してサーバー側だけに保管してください。' },
    pt: { title: 'Sua chave de API do Groq está exposta',
      what: "Uma chave do Groq está visível no seu app. Qualquer pessoa que a encontre pode gerar cobranças de uso na sua conta.",
      fix: "Revogue a chave no console do Groq e crie uma nova, mantendo-a apenas no servidor." },
    fr: { title: 'Une clé API Groq est exposée',
      what: "Une clé Groq est visible dans votre app. Toute personne qui la trouve peut générer des frais d'utilisation sur votre compte.",
      fix: "Révoquez la clé dans votre console Groq et créez-en une nouvelle, à garder uniquement sur le serveur." },
    de: { title: 'Ein Groq-API-Schlüssel ist offengelegt',
      what: 'Ein Groq-Schlüssel ist in Ihrer App sichtbar. Wer ihn findet, kann auf Ihre Kosten Nutzungsgebühren verursachen.',
      fix: 'Widerrufen Sie den Schlüssel in Ihrer Groq-Konsole und erstellen Sie einen neuen, der nur auf dem Server gespeichert wird.' },
    zh: { title: 'Groq API 密钥泄露了',
      what: '应用中暴露了一个 Groq 密钥。任何人都能复制它,把使用费用记到你的账户上。',
      fix: '在你的 Groq 控制台吊销这个密钥,创建一个新密钥,只保存在服务器端。' },
  },
  replicate_token: {
    en: { title: 'A Replicate API token is exposed',
      what: "A Replicate token is visible in your app. Anyone who finds it can run models on your account and rack up usage charges.",
      fix: "Revoke the token in your Replicate account settings and create a new one, kept on the server only." },
    ko: { title: 'Replicate API 토큰이 노출됐습니다',
      what: '앱에 Replicate 토큰이 보입니다. 누구나 복사해 당신 계정으로 모델을 실행시키고 사용 요금을 발생시킬 수 있습니다.',
      fix: 'Replicate 계정 설정에서 토큰을 폐기하고 새로 발급해 서버에만 두세요.' },
    es: { title: 'Tu token de API de Replicate está expuesto',
      what: "Un token de Replicate es visible en tu app. Cualquiera que lo encuentre puede ejecutar modelos con tu cuenta y generar cargos de uso.",
      fix: "Revoca el token en la configuración de tu cuenta de Replicate y crea uno nuevo, manteniéndolo solo en el servidor." },
    ja: { title: 'ReplicateのAPIトークンが漏えいしています',
      what: 'アプリ内にReplicateのトークンが見えています。見つけた人は誰でもあなたのアカウントでモデルを実行し、利用料金を発生させることができます。',
      fix: 'Replicateのアカウント設定でトークンを無効化し、新しいトークンを作成してサーバー側だけに保管してください。' },
    pt: { title: 'Seu token de API do Replicate está exposto',
      what: "Um token do Replicate está visível no seu app. Quem encontrar esse token pode executar modelos na sua conta e gerar cobranças de uso.",
      fix: "Revogue o token nas configurações da sua conta do Replicate e crie um novo, mantendo-o apenas no servidor." },
    fr: { title: 'Un token API Replicate est exposé',
      what: "Un token Replicate est visible dans votre app. Toute personne qui le trouve peut exécuter des modèles sur votre compte et générer des frais d'utilisation.",
      fix: "Révoquez le token dans les paramètres de votre compte Replicate et créez-en un nouveau, à garder uniquement sur le serveur." },
    de: { title: 'Ein Replicate-API-Token ist offengelegt',
      what: 'Ein Replicate-Token ist in Ihrer App sichtbar. Wer es findet, kann über Ihr Konto Modelle ausführen und Nutzungsgebühren verursachen.',
      fix: 'Widerrufen Sie das Token in Ihren Replicate-Kontoeinstellungen und erstellen Sie ein neues, das nur auf dem Server gespeichert wird.' },
    zh: { title: 'Replicate API 令牌泄露了',
      what: '应用中暴露了一个 Replicate 令牌。任何人都能复制它,用你的账户运行模型并产生使用费用。',
      fix: '在你的 Replicate 账户设置中撤销该令牌,重新生成一个新的,只保存在服务器端。' },
  },
};

// severity → human word + color (worst first)
export const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'];
const SEV_META = {
  critical: { color: '#ff5a3c', bg: '#2b1710', border: '#4a2418', en: 'Critical', ko: '심각', es: 'Crítico', ja: '重大', pt: 'Crítico', fr: 'Critique', de: 'Kritisch', zh: '严重' },
  high: { color: '#fb923c', bg: '#2b200f', border: '#4a3418', en: 'High', ko: '높음', es: 'Alto', ja: '高', pt: 'Alto', fr: 'Élevé', de: 'Hoch', zh: '高' },
  medium: { color: '#f4d100', bg: '#262008', border: '#4a3f10', en: 'Medium', ko: '보통', es: 'Medio', ja: '中', pt: 'Médio', fr: 'Moyen', de: 'Mittel', zh: '中' },
  low: { color: '#a6a394', bg: '#17160f', border: '#2e2c1f', en: 'Low', ko: '낮음', es: 'Bajo', ja: '低', pt: 'Baixo', fr: 'Faible', de: 'Niedrig', zh: '低' },
  info: { color: '#a6a394', bg: '#17160f', border: '#2e2c1f', en: 'Info', ko: '참고', es: 'Info', ja: '参考', pt: 'Info', fr: 'Info', de: 'Info', zh: '参考' },
};

export function severityMeta(sev) { return SEV_META[sev] || SEV_META.info; }
export function severityWord(sev, lang) { const m = severityMeta(sev); return m[lang] || m.en; }
export function severityRank(sev) { const i = SEVERITY_ORDER.indexOf(sev); return i === -1 ? 99 : i; }

// Returns { title, what, fix } in the requested language, or null if we have no
// plain-language entry for this rule (caller falls back to the raw label).
export function explain(ruleId, lang) {
  const e = EXPLAIN[ruleId];
  if (!e) return null;
  const copy = e[lang] || e.en;
  return e.snippet ? { ...copy, snippet: e.snippet } : copy;
}
